// src/components/l2/vue/scoretap/ScoretapApp.vue
<!-- @qscrape L2 / vue / scoretap -->
<!-- @component ScoretapApp -->
<template>
  <div v-if="!ready" style="display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:Inter,system-ui;color:#6b7280;background:#0f1117">Loading…</div>
  <div v-else class="st-shell">
    <header class="st-header">
      <div class="st-header-inner">
        <button class="st-logo" @click="navigate('home')">ScoreTap</button>
        <nav class="st-header-nav">
          <button v-for="p in navPages" :key="p.id"
            :class="['st-nav-btn', { 'st-nav-btn--active': page === p.id }]"
            @click="navigate(p.id)">{{ p.label }}</button>
        </nav>
      </div>
    </header>

    <div class="st-game-filter" id="game-filter">
      <button v-for="g in gameFilters" :key="g.id"
        :class="['st-game-tab', { 'st-game-tab--active': activeGame === g.id }]"
        :data-filter="g.id"
        @click="activeGame = g.id">{{ g.label }}</button>
    </div>

    <!-- Home -->
    <main class="st-main" v-if="page === 'home'">
      <div class="st-page-layout">
        <div class="st-main-col">
          <!-- Live scores -->
          <section class="st-widget">
            <div class="st-widget-header"><h2 class="st-widget-title">Live Scores</h2></div>
            <div v-for="m in homeLiveMatches" :key="m.id"
              :class="['st-match-card', 'st-match-card--live']"
              :data-game="m.game"
              :data-match-id="m.id">
              <div class="st-match-team">
                <span class="st-team-name">{{ m.teamA }}</span>
                <span class="st-team-abbr">{{ m.teamAFull }}</span>
              </div>
              <div class="st-match-center">
                <div class="st-score-nums" :id="'score-' + m.id"
                  :data-score-a="liveScores[m.id]?.a ?? m.scoreA"
                  :data-score-b="liveScores[m.id]?.b ?? m.scoreB">
                  {{ liveScores[m.id]?.a ?? m.scoreA }}&nbsp;:&nbsp;{{ liveScores[m.id]?.b ?? m.scoreB }}
                </div>
                <div class="st-match-meta">{{ m.mapOrGame }} · <span class="st-badge-live"><span class="st-live-dot" />LIVE</span></div>
                <div class="st-match-event">{{ m.event }}</div>
                <div class="st-match-game"><span class="st-game-tag" :style="{ '--gc': gameColors[m.game] }">{{ gameLabels[m.game] }}</span></div>
              </div>
              <div class="st-match-team st-match-team--right">
                <span class="st-team-name">{{ m.teamB }}</span>
                <span class="st-team-abbr">{{ m.teamBFull }}</span>
              </div>
            </div>
          </section>

          <!-- Recent results -->
          <section class="st-widget">
            <div class="st-widget-header"><h2 class="st-widget-title">Recent Results</h2></div>
            <div v-for="m in homeRecentResults" :key="m.id" class="st-match-card" :data-game="m.game" :data-match-id="m.id">
              <div class="st-match-team">
                <span class="st-team-name">{{ m.teamA }}</span>
                <span class="st-team-abbr">{{ m.teamAFull }}</span>
              </div>
              <div class="st-match-center">
                <div class="st-score-nums">{{ m.scoreA }}&nbsp;:&nbsp;{{ m.scoreB }}</div>
                <div class="st-match-meta"><span class="st-badge-final">FINAL</span></div>
                <div class="st-match-event">{{ m.event }}</div>
                <div class="st-match-game"><span class="st-game-tag" :style="{ '--gc': gameColors[m.game] }">{{ gameLabels[m.game] }}</span></div>
              </div>
              <div class="st-match-team st-match-team--right">
                <span class="st-team-name">{{ m.teamB }}</span>
                <span class="st-team-abbr">{{ m.teamBFull }}</span>
              </div>
            </div>
          </section>

          <!-- News -->
          <section class="st-widget">
            <div class="st-widget-header"><h2 class="st-widget-title">Latest News</h2></div>
            <div class="st-news-grid">
              <div v-for="item in homeNewsItems" :key="item.id" class="st-news-card" :data-game="item.game">
                <a class="st-news-headline" href="#">{{ item.headline }}</a>
                <div class="st-news-meta">
                  <span class="st-game-tag" :style="{ '--gc': gameColors[item.game] }">{{ gameLabels[item.game] }}</span>
                  <span>{{ item.hoursAgo }}h ago</span>
                </div>
              </div>
            </div>
          </section>
        </div>

        <div class="st-sidebar">
          <!-- Upcoming -->
          <section class="st-widget">
            <div class="st-widget-header"><h2 class="st-widget-title">Upcoming</h2></div>
            <div v-for="m in homeUpcoming" :key="m.id" class="st-upcoming-card" :data-game="m.game">
              <div>
                <div class="st-upcoming-teams">{{ m.teamA }} vs {{ m.teamB }}</div>
                <div style="margin-top:4px;"><span class="st-game-tag" :style="{ '--gc': gameColors[m.game] }">{{ gameLabels[m.game] }}</span></div>
              </div>
              <div class="st-upcoming-time">
                <span class="st-badge-upcoming">UPCOMING</span>
                <div style="margin-top:4px;font-size:12px;">{{ m.time }}</div>
              </div>
            </div>
          </section>

          <!-- CS2 Rankings -->
          <section v-if="showCs2Rankings" class="st-widget">
            <div class="st-widget-header"><h2 class="st-widget-title">CS2 World Rankings</h2></div>
            <div v-for="r in cs2Rankings" :key="r.rank" class="st-rank-row">
              <span class="st-rank-num">#{{ r.rank }}</span>
              <span class="st-rank-team">{{ r.team }}</span>
              <span class="st-rank-pts">{{ r.points.toLocaleString() }} pts</span>
              <span :class="['st-rank-change', 'st-change-' + r.change]">
                {{ r.change === 'up' ? '▲' + r.delta : r.change === 'down' ? '▼' + r.delta : '—' }}
              </span>
            </div>
          </section>

          <!-- Events -->
          <section class="st-widget">
            <div class="st-widget-header"><h2 class="st-widget-title">Top Events</h2></div>
            <div v-for="ev in topEvents" :key="ev.id" class="st-event-row" :data-game="ev.game">
              <div class="st-event-name">{{ ev.name }}</div>
              <div class="st-event-right">
                <span class="st-game-tag" :style="{ '--gc': gameColors[ev.game] }">{{ gameLabels[ev.game] }}</span>
                <div class="st-event-dates">{{ ev.dates }}</div>
              </div>
              <span :class="ev.status === 'live' ? 'st-badge-live-sm' : 'st-badge-upcoming-sm'">{{ ev.status.toUpperCase() }}</span>
            </div>
          </section>
        </div>
      </div>
    </main>

    <!-- Events -->
    <main class="st-main" v-else-if="page === 'events'">
      <div class="st-full-col">
        <h1 class="st-page-title">Events</h1>
        <div class="st-filter-tabs">
          <button v-for="g in gameFilters" :key="g.id"
            :class="['st-filter-tab', { 'st-filter-tab--active': activeGame === g.id }]"
            @click="activeGame = g.id">{{ g.label }}</button>
        </div>
        <div class="st-events-table">
          <div v-for="ev in filteredEvents" :key="ev.id" class="st-event-table-row" :data-game="ev.game" :data-event-id="ev.id">
            <div class="st-event-table-name">{{ ev.name }}</div>
            <span class="st-game-tag" :style="{ '--gc': gameColors[ev.game] }">{{ gameLabels[ev.game] }}</span>
            <div class="st-event-table-dates">{{ ev.dates }}</div>
            <span :class="'st-badge-' + ev.status">{{ ev.status.toUpperCase() }}</span>
          </div>
        </div>
      </div>
    </main>

    <!-- Teams -->
    <main class="st-main" v-else-if="page === 'teams'">
      <div class="st-full-col">
        <h1 class="st-page-title">Teams</h1>
        <div class="st-filter-tabs">
          <button v-for="g in gameFilters" :key="g.id"
            :class="['st-filter-tab', { 'st-filter-tab--active': activeGame === g.id }]"
            @click="activeGame = g.id">{{ g.label }}</button>
        </div>
        <div class="st-teams-grid">
          <div v-for="t in filteredTeams" :key="t.id" class="st-team-card" :data-team-id="t.id" :data-game="t.game">
            <div class="st-team-card-name">{{ t.name }}</div>
            <div class="st-team-card-abbr">{{ t.abbr }}</div>
            <span class="st-game-tag" :style="{ '--gc': gameColors[t.game] }">{{ gameLabels[t.game] }}</span>
            <div v-if="t.rank" class="st-team-card-rank">Rank #{{ t.rank }} · {{ t.rankPoints?.toLocaleString() }} pts</div>
          </div>
        </div>
      </div>
    </main>

    <footer class="st-footer">
      <div class="st-footer-inner">&copy; 2026 ScoreTap. QScrape L2 Test Site.</div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { fakeGet } from '../../../../data/api';
import type { Game } from '../../../../data/scoretap/data';
import {
	events,
	liveMatches,
	newsItems,
	recentResults,
	teams,
	upcomingMatches,
} from '../../../../data/scoretap/data';

type Page = 'home' | 'events' | 'teams';

// ── URL routing helpers ────────────────────────────────────────────────────
function getBase() {
	return `/${window.location.pathname.split('/').filter(Boolean).slice(0, 3).join('/')}/`;
}
function pathToPage(): Page {
	const seg = window.location.pathname.split('/').filter(Boolean).at(-1) ?? '';
	if (seg === 'events') {
		return 'events';
	}
	if (seg === 'teams') {
		return 'teams';
	}
	return 'home';
}
function pageToPath(p: Page) {
	const base = getBase();
	if (p === 'events') {
		return `${base}events`;
	}
	if (p === 'teams') {
		return `${base}teams`;
	}
	return base;
}

const ready = ref(false);
const page = ref<Page>('home');
const activeGame = ref<Game | 'all'>('all');

const _navPages = [
	{ id: 'home' as Page, label: 'Home' },
	{ id: 'events' as Page, label: 'Events' },
	{ id: 'teams' as Page, label: 'Teams' },
];
const _gameFilters = [
	{ id: 'all' as Game | 'all', label: 'All Games' },
	{ id: 'cs2' as Game, label: 'CS2' },
	{ id: 'valorant' as Game, label: 'Valorant' },
	{ id: 'lol' as Game, label: 'LoL' },
	{ id: 'dota2' as Game, label: 'Dota 2' },
	{ id: 'rl' as Game, label: 'Rocket League' },
];

// Live scores
const liveScores = ref<Record<string, { a: number; b: number }>>(
	Object.fromEntries(
		liveMatches.map((m) => [m.id, { a: m.scoreA, b: m.scoreB }]),
	),
);
const caps: Record<string, number> = {
	'match-001': 30,
	'match-002': 30,
	'match-003': 5,
};
const interval = setInterval(() => {
	const keys = Object.keys(liveScores.value);
	const key = keys[Math.floor(Math.random() * keys.length)];
	const side = Math.random() < 0.5 ? 'a' : 'b';
	const cap = caps[key] || 30;
	const cur = liveScores.value[key][side];
	if (cur < cap) {
		liveScores.value[key] = { ...liveScores.value[key], [side]: cur + 1 };
	}
}, 8000);
onUnmounted(() => clearInterval(interval));

const gf = (arr: { game: Game }[]) =>
	activeGame.value === 'all'
		? arr
		: arr.filter((x) => x.game === activeGame.value);
const _homeLiveMatches = computed(() => gf(liveMatches));
const _homeRecentResults = computed(() => gf(recentResults));
const _homeNewsItems = computed(() => gf(newsItems).slice(0, 8));
const _homeUpcoming = computed(() => gf(upcomingMatches));
const _topEvents = computed(() =>
	gf(events.filter((e) => e.status !== 'completed')).slice(0, 5),
);
const _showCs2Rankings = computed(
	() => activeGame.value === 'all' || activeGame.value === 'cs2',
);
const _filteredEvents = computed(() =>
	activeGame.value === 'all'
		? events
		: events.filter((e) => e.game === activeGame.value),
);
const _filteredTeams = computed(() =>
	activeGame.value === 'all'
		? teams
		: teams.filter((t) => t.game === activeGame.value),
);

function _navigate(p: Page) {
	page.value = p;
	history.pushState(null, '', pageToPath(p));
	window.scrollTo(0, 0);
}

function onPop() {
	page.value = pathToPage();
	window.scrollTo(0, 0);
}
onMounted(() => {
	page.value = pathToPage();
	window.addEventListener('popstate', onPop);
	fakeGet(null).then(() => {
		ready.value = true;
	});
});
onUnmounted(() => window.removeEventListener('popstate', onPop));
</script>

<style scoped>
.st-shell { min-height: 100vh; background: #0f1117; color: #e8e8f0; font-family: 'Inter', system-ui, sans-serif; }
.st-header { background: #1a1d27; border-bottom: 1px solid #2d3148; }
.st-header-inner { max-width: 1200px; margin: 0 auto; padding: 0 24px; display: flex; align-items: center; gap: 32px; }
.st-logo { background: none; border: none; cursor: pointer; font-size: 22px; font-weight: 700; color: #22c55e; padding: 14px 0; font-family: 'Roboto Mono', monospace; letter-spacing: -0.5px; }
.st-header-nav { display: flex; }
.st-nav-btn { background: none; border: none; cursor: pointer; padding: 16px 14px; font-size: 14px; color: #6b7280; border-bottom: 2px solid transparent; font-weight: 500; }
.st-nav-btn:hover { color: #e8e8f0; }
.st-nav-btn--active { color: #e8e8f0; border-bottom-color: #22c55e; }
.st-game-filter { background: #21253a; border-bottom: 1px solid #2d3148; display: flex; overflow-x: auto; }
.st-game-tab { background: none; border: none; cursor: pointer; padding: 10px 16px; font-size: 13px; color: #6b7280; white-space: nowrap; border-bottom: 2px solid transparent; font-weight: 500; }
.st-game-tab:hover { color: #e8e8f0; }
.st-game-tab--active { color: #e8e8f0; border-bottom-color: #22c55e; }
.st-main { max-width: 1200px; margin: 0 auto; padding: 24px; }
.st-page-layout { display: grid; grid-template-columns: 1fr 300px; gap: 24px; }
@media (max-width: 900px) { .st-page-layout { grid-template-columns: 1fr; } }
.st-main-col { display: flex; flex-direction: column; gap: 20px; }
.st-sidebar { display: flex; flex-direction: column; gap: 20px; }
.st-full-col { }
.st-widget { background: #1a1d27; border: 1px solid #2d3148; border-radius: 6px; overflow: hidden; }
.st-widget-header { padding: 12px 16px; border-bottom: 1px solid #2d3148; }
.st-widget-title { font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280; }
.st-game-tag { display: inline-block; font-size: 10px; font-weight: 700; padding: 2px 6px; border-radius: 3px; color: var(--gc, #fff); border: 1px solid var(--gc, #fff); opacity: 0.85; text-transform: uppercase; letter-spacing: 0.04em; }
.st-badge-live { display: inline-flex; align-items: center; gap: 4px; font-size: 10px; font-weight: 700; padding: 2px 6px; background: rgba(34,197,94,0.15); color: #22c55e; border-radius: 3px; text-transform: uppercase; }
.st-live-dot { width: 6px; height: 6px; background: #22c55e; border-radius: 50%; animation: pulse 1.5s ease-in-out infinite; display: inline-block; }
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
.st-badge-final { display: inline-block; font-size: 10px; font-weight: 700; padding: 2px 6px; background: rgba(107,114,128,0.2); color: #6b7280; border-radius: 3px; text-transform: uppercase; }
.st-badge-upcoming { display: inline-block; font-size: 10px; font-weight: 700; padding: 2px 6px; background: rgba(91,156,246,0.15); color: #5b9cf6; border-radius: 3px; text-transform: uppercase; }
.st-badge-live-sm, .st-badge-upcoming-sm, .st-badge-completed { display: inline-block; font-size: 10px; font-weight: 700; padding: 2px 6px; border-radius: 3px; text-transform: uppercase; }
.st-badge-live-sm { background: rgba(34,197,94,0.15); color: #22c55e; }
.st-badge-upcoming-sm { background: rgba(91,156,246,0.15); color: #5b9cf6; }
.st-badge-completed { background: rgba(107,114,128,0.15); color: #6b7280; }
.st-match-card { display: grid; grid-template-columns: 1fr auto 1fr; gap: 16px; padding: 14px 16px; border-bottom: 1px solid #2d3148; align-items: center; }
.st-match-card:last-child { border-bottom: none; }
.st-match-card--live { background: rgba(34,197,94,0.04); }
.st-match-team { display: flex; flex-direction: column; gap: 2px; }
.st-match-team--right { text-align: right; align-items: flex-end; }
.st-team-name { font-size: 15px; font-weight: 700; font-family: 'Roboto Mono', monospace; }
.st-team-abbr { font-size: 11px; color: #6b7280; }
.st-match-center { text-align: center; min-width: 100px; }
.st-score-nums { font-family: 'Roboto Mono', monospace; font-size: 22px; font-weight: 700; letter-spacing: 2px; margin-bottom: 4px; }
.st-match-meta { font-size: 11px; color: #6b7280; margin-bottom: 3px; }
.st-match-event { font-size: 11px; color: #6b7280; margin-bottom: 3px; }
.st-news-grid { display: grid; grid-template-columns: 1fr 1fr; }
@media (max-width: 600px) { .st-news-grid { grid-template-columns: 1fr; } }
.st-news-card { padding: 12px 16px; border-bottom: 1px solid #2d3148; border-right: 1px solid #2d3148; }
.st-news-card:nth-child(even) { border-right: none; }
.st-news-headline { display: block; font-size: 13px; color: #e8e8f0; line-height: 1.4; margin-bottom: 6px; }
.st-news-headline:hover { color: #fff; }
.st-news-meta { display: flex; align-items: center; gap: 8px; font-size: 11px; color: #6b7280; }
.st-upcoming-card { display: flex; justify-content: space-between; align-items: center; padding: 12px 16px; border-bottom: 1px solid #2d3148; }
.st-upcoming-card:last-child { border-bottom: none; }
.st-upcoming-teams { font-size: 13px; font-weight: 600; margin-bottom: 4px; }
.st-upcoming-time { text-align: right; }
.st-rank-row { display: grid; grid-template-columns: 30px 1fr auto 40px; gap: 8px; padding: 8px 16px; border-bottom: 1px solid #2d3148; align-items: center; font-size: 13px; }
.st-rank-row:last-child { border-bottom: none; }
.st-rank-num { color: #6b7280; font-weight: 700; }
.st-rank-team { font-weight: 600; }
.st-rank-pts { color: #6b7280; font-family: 'Roboto Mono', monospace; font-size: 12px; }
.st-rank-change { font-size: 11px; font-weight: 700; text-align: right; }
.st-change-up { color: #22c55e; }
.st-change-down { color: #ef4444; }
.st-change-same { color: #6b7280; }
.st-event-row { display: grid; grid-template-columns: 1fr auto auto; gap: 12px; padding: 12px 16px; border-bottom: 1px solid #2d3148; align-items: center; }
.st-event-row:last-child { border-bottom: none; }
.st-event-name { font-size: 13px; font-weight: 600; }
.st-event-right { text-align: right; }
.st-event-dates { font-size: 11px; color: #6b7280; margin-top: 3px; }
.st-page-title { font-size: 24px; font-weight: 700; margin-bottom: 24px; }
.st-filter-tabs { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 20px; }
.st-filter-tab { background: #1a1d27; border: 1px solid #2d3148; cursor: pointer; padding: 6px 14px; font-size: 13px; color: #6b7280; border-radius: 6px; }
.st-filter-tab:hover { color: #e8e8f0; border-color: #e8e8f0; }
.st-filter-tab--active { background: #22c55e; border-color: #22c55e; color: #000; font-weight: 600; }
.st-events-table { display: flex; flex-direction: column; border: 1px solid #2d3148; border-radius: 6px; overflow: hidden; }
.st-event-table-row { display: grid; grid-template-columns: 1fr auto auto auto; gap: 16px; padding: 14px 16px; border-bottom: 1px solid #2d3148; align-items: center; }
.st-event-table-row:last-child { border-bottom: none; }
.st-event-table-name { font-size: 14px; font-weight: 600; }
.st-event-table-dates { font-size: 13px; color: #6b7280; }
.st-teams-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; }
@media (max-width: 900px) { .st-teams-grid { grid-template-columns: repeat(3, 1fr); } }
@media (max-width: 600px) { .st-teams-grid { grid-template-columns: repeat(2, 1fr); } }
.st-team-card { background: #1a1d27; border: 1px solid #2d3148; border-radius: 6px; padding: 16px; }
.st-team-card-name { font-size: 15px; font-weight: 700; margin-bottom: 2px; }
.st-team-card-abbr { font-size: 12px; color: #6b7280; margin-bottom: 8px; }
.st-team-card-rank { font-size: 12px; color: #6b7280; margin-top: 8px; font-family: 'Roboto Mono', monospace; }
.st-footer { border-top: 1px solid #2d3148; margin-top: 48px; }
.st-footer-inner { max-width: 1200px; margin: 0 auto; padding: 16px 24px; font-size: 12px; color: #6b7280; }
</style>

// src/components/l2/svelte/scoretap/ScoretapApp.svelte
<script lang="ts">
// @qscrape L2 / svelte / scoretap — ScoreTap
import { onDestroy, onMount } from 'svelte';
import '../../../../styles/l2/scoretap.css';
import { fakeGet } from '../../../../data/api';
import {
	events,
	type Game,
	gameLabels,
	liveMatches,
	newsItems,
	teams,
} from '../../../../data/scoretap/data';

type Page = 'home' | 'events' | 'teams';

function getBase(): string {
	return `/${window.location.pathname.split('/').filter(Boolean).slice(0, 3).join('/')}/`;
}
function urlToPage(): Page {
	const seg = window.location.pathname.split('/').filter(Boolean).at(-1) ?? '';
	if (seg === 'events') {
		return 'events';
	}
	if (seg === 'teams') {
		return 'teams';
	}
	return 'home';
}
function pageToUrl(p: Page): string {
	const base = getBase();
	if (p === 'events') {
		return `${base}events`;
	}
	if (p === 'teams') {
		return `${base}teams`;
	}
	return base;
}

let _ready = false;
let _current: Page = 'home';

const _games = Object.keys(gameLabels) as Game[];
const gameFilter: Game | 'all' = 'all';

// Live score ticker
let liveTicker = liveMatches.map((m) => ({ ...m }));
const ticker = setInterval(() => {
	liveTicker = liveTicker.map((m) => ({
		...m,
		scoreA: m.scoreA + (Math.random() < 0.15 ? 1 : 0),
		scoreB: m.scoreB + (Math.random() < 0.12 ? 1 : 0),
	}));
}, 8000);
onDestroy(() => clearInterval(ticker));

function _nav(p: Page) {
	_current = p;
	history.pushState(null, '', pageToUrl(p));
	window.scrollTo(0, 0);
}

function onPop() {
	_current = urlToPage();
	window.scrollTo(0, 0);
}
onMount(() => {
	_current = urlToPage();
	window.addEventListener('popstate', onPop);
	fakeGet(null).then(() => {
		_ready = true;
	});
});
onDestroy(() => window.removeEventListener('popstate', onPop));

$: filteredTeams =
	gameFilter === 'all' ? teams : teams.filter((t) => t.game === gameFilter);
$: filteredEvents =
	gameFilter === 'all' ? events : events.filter((e) => e.game === gameFilter);
$: filteredNews =
	gameFilter === 'all'
		? newsItems
		: newsItems.filter((n) => n.game === gameFilter);

function _gcVar(game: Game) {
	return `var(--st-${game})`;
}
</script>

{#if !ready}
  <div style="display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:Inter,system-ui;color:#6b7280;background:#0f1117">Loading…</div>
{:else}
<div class="st-shell">
  <!-- Header -->
  <header class="st-header">
    <div class="st-header-inner">
      <button class="st-logo" on:click={() => nav('home')}>⚡ ScoreTap</button>
      <nav class="st-main-nav">
        <button class="st-nav-btn{current === 'home' ? ' active' : ''}" on:click={() => nav('home')}>Home</button>
        <button class="st-nav-btn{current === 'events' ? ' active' : ''}" on:click={() => nav('events')}>Events</button>
        <button class="st-nav-btn{current === 'teams' ? ' active' : ''}" on:click={() => nav('teams')}>Teams</button>
      </nav>
    </div>
    <!-- Game filter tabs -->
    <div class="st-game-tabs">
      <button class="st-game-tab{gameFilter === 'all' ? ' active' : ''}" on:click={() => (gameFilter = 'all')}>All Games</button>
      {#each games as g}
        <button
          class="st-game-tab{gameFilter === g ? ' active' : ''}"
          style="--gc: {gameColors[g]}"
          on:click={() => (gameFilter = g === gameFilter ? 'all' : g)}
        >{gameLabels[g]}</button>
      {/each}
    </div>
  </header>

  <main class="st-main">
    <!-- HOME PAGE -->
    {#if current === 'home'}
      <!-- Live matches -->
      <section class="st-section">
        <h2 class="st-section-title"><span class="st-live-dot"></span> Live Now</h2>
        <div class="st-match-list">
          {#each liveTicker.filter((m) => gameFilter === 'all' || m.game === gameFilter) as m (m.id)}
            <div class="st-match-card st-live" data-id={m.id} data-game={m.game}>
              <div class="st-game-tag" style="color: {gameColors[m.game]}">{gameLabels[m.game]}</div>
              <div class="st-match-body">
                <div class="st-team-row">
                  <span class="st-team-name">{m.teamAFull}</span>
                  <span class="st-score" data-score-a>{m.scoreA}</span>
                </div>
                <div class="st-vs-row">
                  <span class="st-map-label">{m.mapOrGame}</span>
                  <span class="st-status-live">LIVE</span>
                </div>
                <div class="st-team-row">
                  <span class="st-team-name">{m.teamBFull}</span>
                  <span class="st-score" data-score-b>{m.scoreB}</span>
                </div>
              </div>
              <div class="st-event-label">{m.event}</div>
            </div>
          {/each}
        </div>
      </section>

      <!-- Recent Results -->
      <section class="st-section">
        <h2 class="st-section-title">Recent Results</h2>
        <div class="st-results-list">
          {#each recentResults.filter((m) => gameFilter === 'all' || m.game === gameFilter) as m}
            <div class="st-result-row" data-id={m.id} data-game={m.game}>
              <span class="st-game-tag-sm" style="color: {gameColors[m.game]}">{gameLabels[m.game]}</span>
              <span class="st-team-a">{m.teamAFull}</span>
              <span class="st-result-score" data-score>{m.scoreA} – {m.scoreB}</span>
              <span class="st-team-b">{m.teamBFull}</span>
              <span class="st-event-sm">{m.event}</span>
              <span class="st-status-final">FINAL</span>
            </div>
          {/each}
        </div>
      </section>

      <!-- Upcoming -->
      <section class="st-section">
        <h2 class="st-section-title">Upcoming Matches</h2>
        <div class="st-results-list">
          {#each upcomingMatches.filter((m) => gameFilter === 'all' || m.game === gameFilter) as m}
            <div class="st-result-row" data-id={m.id} data-game={m.game}>
              <span class="st-game-tag-sm" style="color: {gameColors[m.game]}">{gameLabels[m.game]}</span>
              <span class="st-team-a">{m.teamAFull}</span>
              <span class="st-result-score">vs</span>
              <span class="st-team-b">{m.teamBFull}</span>
              <span class="st-event-sm">{m.event}</span>
              <span class="st-time">{m.time}</span>
            </div>
          {/each}
        </div>
      </section>

      <!-- News feed -->
      <section class="st-section">
        <h2 class="st-section-title">Latest News</h2>
        <ul class="st-news-list">
          {#each filteredNews as n}
            <li class="st-news-item" data-id={n.id} data-game={n.game}>
              <span class="st-game-tag-sm" style="color: {gameColors[n.game]}">{gameLabels[n.game]}</span>
              <span class="st-news-headline">{n.headline}</span>
              <span class="st-news-time">{n.hoursAgo}h ago</span>
            </li>
          {/each}
        </ul>
      </section>

      <!-- CS2 Rankings -->
      {#if gameFilter === 'all' || gameFilter === 'cs2'}
        <section class="st-section">
          <h2 class="st-section-title" style="color: var(--st-cs2)">CS2 World Rankings</h2>
          <table class="st-rankings-table">
            <thead>
              <tr><th>#</th><th>Team</th><th>Points</th><th>Change</th></tr>
            </thead>
            <tbody>
              {#each cs2Rankings as r}
                <tr data-rank={r.rank} data-team={r.team}>
                  <td class="st-rank-num">{r.rank}</td>
                  <td class="st-rank-team">{r.team}</td>
                  <td class="st-rank-pts">{r.points.toLocaleString()}</td>
                  <td class="st-rank-change">
                    {#if r.change === 'up'}
                      <span class="st-up">▲ {r.delta}</span>
                    {:else if r.change === 'down'}
                      <span class="st-down">▼ {r.delta}</span>
                    {:else}
                      <span class="st-same">—</span>
                    {/if}
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </section>
      {/if}

    <!-- EVENTS PAGE -->
    {:else if current === 'events'}
      <section class="st-section">
        <h2 class="st-section-title">Events</h2>
        <div class="st-events-grid">
          {#each filteredEvents as ev}
            <div class="st-event-card" data-id={ev.id} data-game={ev.game}>
              <div class="st-game-tag" style="color: {gameColors[ev.game]}">{gameLabels[ev.game]}</div>
              <h3 class="st-event-name">{ev.name}</h3>
              <p class="st-event-dates">{ev.dates}</p>
              {#if ev.status === 'live'}
                <span class="st-status-live">LIVE</span>
              {:else if ev.status === 'upcoming'}
                <span class="st-status-upcoming">Upcoming</span>
              {:else}
                <span class="st-status-final">Completed</span>
              {/if}
            </div>
          {/each}
        </div>
      </section>

    <!-- TEAMS PAGE -->
    {:else if current === 'teams'}
      <section class="st-section">
        <h2 class="st-section-title">Teams</h2>
        <div class="st-teams-grid">
          {#each filteredTeams as t}
            <div class="st-team-card" data-id={t.id} data-game={t.game}>
              <div class="st-game-tag" style="color: {gameColors[t.game]}">{gameLabels[t.game]}</div>
              <h3 class="st-team-name-full">{t.name}</h3>
              <p class="st-team-abbr">{t.abbr}</p>
              {#if t.rank}
                <p class="st-team-rank">Rank #{t.rank} · {t.rankPoints?.toLocaleString()} pts</p>
              {/if}
            </div>
          {/each}
        </div>
      </section>
    {/if}
  </main>

  <footer class="st-footer">
    <p>© 2026 ScoreTap · Esports Scores & Coverage · Data updates every 8s</p>
  </footer>
</div>
{/if}

<style>
  .st-shell { min-height: 100vh; display: flex; flex-direction: column; }

  /* Header */
  .st-header { background: var(--st-surface); border-bottom: 1px solid var(--st-border); position: sticky; top: 0; z-index: 100; }
  .st-header-inner { max-width: 1200px; margin: 0 auto; padding: 12px 24px; display: flex; align-items: center; gap: 24px; }
  .st-logo { background: none; border: none; color: var(--st-text); font-family: var(--st-font-score); font-size: 1.3rem; font-weight: 700; cursor: pointer; letter-spacing: -0.01em; }
  .st-main-nav { display: flex; gap: 4px; }
  .st-nav-btn { background: none; border: none; color: var(--st-muted); font-family: var(--st-font-ui); font-size: 13px; padding: 5px 14px; border-radius: var(--st-radius); cursor: pointer; }
  .st-nav-btn:hover, .st-nav-btn.active { background: var(--st-surface2); color: var(--st-text); }
  .st-game-tabs { max-width: 1200px; margin: 0 auto; padding: 6px 24px; display: flex; flex-wrap: wrap; gap: 4px; }
  .st-game-tab { background: none; border: 1px solid var(--st-border); color: var(--st-muted); font-family: var(--st-font-ui); font-size: 12px; padding: 3px 12px; border-radius: 20px; cursor: pointer; }
  .st-game-tab:hover { border-color: var(--gc, var(--st-live)); color: var(--gc, var(--st-live)); }
  .st-game-tab.active { background: var(--gc, var(--st-live)); border-color: var(--gc, var(--st-live)); color: #000; font-weight: 600; }

  /* Main */
  .st-main { flex: 1; max-width: 1200px; margin: 0 auto; width: 100%; padding: 24px; }
  .st-section { margin-bottom: 36px; }
  .st-section-title { font-size: 1rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; color: var(--st-muted); margin-bottom: 16px; display: flex; align-items: center; gap: 8px; }

  /* Live dot */
  .st-live-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; background: var(--st-live); box-shadow: 0 0 0 3px var(--st-live-dim); animation: pulse 1.5s infinite; }
  @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }

  /* Match cards */
  .st-match-list { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; }
  .st-match-card { background: var(--st-surface); border: 1px solid var(--st-border); border-radius: var(--st-radius); padding: 16px; }
  .st-match-card.st-live { border-left: 3px solid var(--st-live); }
  .st-game-tag { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 10px; }
  .st-match-body { display: flex; flex-direction: column; gap: 4px; }
  .st-team-row { display: flex; justify-content: space-between; align-items: center; }
  .st-team-name { font-size: 14px; font-weight: 600; }
  .st-score { font-family: var(--st-font-score); font-size: 1.4rem; font-weight: 700; color: var(--st-text); }
  .st-vs-row { display: flex; justify-content: space-between; align-items: center; padding: 2px 0; }
  .st-map-label { font-size: 11px; color: var(--st-muted); }
  .st-status-live { font-size: 11px; font-weight: 700; color: var(--st-live); letter-spacing: 0.08em; }
  .st-event-label { font-size: 11px; color: var(--st-muted); margin-top: 12px; }

  /* Results list */
  .st-results-list { display: flex; flex-direction: column; gap: 2px; }
  .st-result-row { background: var(--st-surface); border: 1px solid var(--st-border); border-radius: var(--st-radius); padding: 10px 16px; display: grid; grid-template-columns: 80px 1fr auto 1fr 1fr auto; align-items: center; gap: 8px; font-size: 13px; }
  .st-game-tag-sm { font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; }
  .st-result-score { font-family: var(--st-font-score); font-weight: 700; text-align: center; color: var(--st-text); }
  .st-team-a { text-align: right; }
  .st-event-sm { font-size: 11px; color: var(--st-muted); }
  .st-status-final { font-size: 10px; font-weight: 600; color: var(--st-muted); letter-spacing: 0.06em; }
  .st-status-upcoming { font-size: 10px; font-weight: 600; color: #60a5fa; letter-spacing: 0.06em; }
  .st-time { font-size: 11px; color: #60a5fa; }

  /* News */
  .st-news-list { list-style: none; display: flex; flex-direction: column; gap: 2px; }
  .st-news-item { background: var(--st-surface); border: 1px solid var(--st-border); border-radius: var(--st-radius); padding: 10px 16px; display: flex; align-items: center; gap: 12px; }
  .st-news-headline { flex: 1; font-size: 13px; }
  .st-news-time { font-size: 11px; color: var(--st-muted); white-space: nowrap; }

  /* Rankings */
  .st-rankings-table { width: 100%; border-collapse: collapse; }
  .st-rankings-table th { text-align: left; font-size: 11px; color: var(--st-muted); letter-spacing: 0.06em; text-transform: uppercase; padding: 8px 12px; border-bottom: 1px solid var(--st-border); }
  .st-rankings-table tr:hover td { background: var(--st-surface2); }
  .st-rankings-table td { padding: 10px 12px; border-bottom: 1px solid var(--st-border); font-size: 13px; }
  .st-rank-num { font-family: var(--st-font-score); font-weight: 700; color: var(--st-muted); width: 40px; }
  .st-rank-team { font-weight: 600; }
  .st-rank-pts { font-family: var(--st-font-score); }
  .st-up { color: var(--st-live); font-size: 12px; }
  .st-down { color: #ef4444; font-size: 12px; }
  .st-same { color: var(--st-muted); font-size: 12px; }

  /* Events */
  .st-events-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 16px; }
  .st-event-card { background: var(--st-surface); border: 1px solid var(--st-border); border-radius: var(--st-radius); padding: 16px; }
  .st-event-name { font-size: 1rem; font-weight: 600; margin: 8px 0 4px; }
  .st-event-dates { font-size: 12px; color: var(--st-muted); margin-bottom: 8px; }

  /* Teams */
  .st-teams-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 12px; }
  .st-team-card { background: var(--st-surface); border: 1px solid var(--st-border); border-radius: var(--st-radius); padding: 14px; }
  .st-team-name-full { font-size: 1rem; font-weight: 600; margin: 8px 0 2px; }
  .st-team-abbr { font-family: var(--st-font-score); font-size: 11px; color: var(--st-muted); margin-bottom: 4px; }
  .st-team-rank { font-size: 12px; color: var(--st-muted); }

  /* Footer */
  .st-footer { background: var(--st-surface); border-top: 1px solid var(--st-border); text-align: center; padding: 16px 24px; font-size: 12px; color: var(--st-muted); }
</style>
