// src/components/l2/svelte/eshop/EshopApp.svelte
<script lang="ts">
// @qscrape L2 / svelte / eshop — VaultMart
import { onDestroy, onMount } from 'svelte';
import '../../../../styles/l2/eshop.css';

import { fakeGet } from '../../../../data/api';
import {
	getByCategory,
	getProductBySku,
	type ProductMeta,
	products,
} from '../../../../data/eshop/products';

type Page =
	| { name: 'home' }
	| { name: 'catalog'; category?: string }
	| { name: 'product'; sku: string }
	| { name: 'cart' }
	| { name: 'search'; query: string };

interface CartItem {
	sku: string;
	qty: number;
	price: number;
	name: string;
}

function getBase(): string {
	return `/${window.location.pathname.split('/').filter(Boolean).slice(0, 3).join('/')}/`;
}
function urlToPage(): Page {
	const seg = window.location.pathname.split('/').filter(Boolean).at(-1) ?? '';
	const p = new URLSearchParams(window.location.search);
	if (seg === 'catalog') {
		return { name: 'catalog', category: p.get('cat') ?? undefined };
	}
	if (seg === 'product') {
		return { name: 'product', sku: p.get('sku') ?? '' };
	}
	if (seg === 'cart') {
		return { name: 'cart' };
	}
	if (seg === 'search') {
		return { name: 'search', query: p.get('q') ?? '' };
	}
	return { name: 'home' };
}
function pageToUrl(p: Page): string {
	const base = getBase();
	if (p.name === 'catalog') {
		return `${base}catalog${p.category ? `?cat=${encodeURIComponent(p.category)}` : ''}`;
	}
	if (p.name === 'product') {
		return `${base}product?sku=${encodeURIComponent(p.sku)}`;
	}
	if (p.name === 'cart') {
		return `${base}cart`;
	}
	if (p.name === 'search') {
		return `${base}search?q=${encodeURIComponent(p.query)}`;
	}
	return base;
}

let _ready = false;
let current: Page = { name: 'home' };
let cart: CartItem[] = [
	{ sku: 'VM-MIN-001', qty: 2, price: 14.5, name: 'Standard Iron Pickaxe' },
	{
		sku: 'VM-FDB-002',
		qty: 1,
		price: 18.0,
		name: 'Dwarven Ale (6-flagon case)',
	},
	{
		sku: 'VM-FRG-001',
		qty: 1,
		price: 12.0,
		name: 'Iron Ingot Bundle (10-bar)',
	},
];
let searchQuery = '';

function nav(p: Page) {
	current = p;
	history.pushState(null, '', pageToUrl(p));
	window.scrollTo(0, 0);
}

function onPop() {
	current = urlToPage();
	window.scrollTo(0, 0);
}
onMount(() => {
	current = urlToPage();
	window.addEventListener('popstate', onPop);
	fakeGet(null).then(() => {
		_ready = true;
	});
});
onDestroy(() => window.removeEventListener('popstate', onPop));

function _addToCart(product: ProductMeta) {
	const existing = cart.find((c) => c.sku === product.sku);
	if (existing) {
		cart = cart.map((c) =>
			c.sku === product.sku ? { ...c, qty: c.qty + 1 } : c,
		);
	} else {
		cart = [
			...cart,
			{
				sku: product.sku,
				qty: 1,
				price: product.salePrice ?? product.basePrice,
				name: product.name,
			},
		];
	}
}

function _updateQty(sku: string, qty: number) {
	if (qty < 1) {
		cart = cart.filter((c) => c.sku !== sku);
		return;
	}
	cart = cart.map((c) => (c.sku === sku ? { ...c, qty } : c));
}

$: cartTotal = cart.reduce((s, c) => s + c.price * c.qty, 0);
$: cartCount = cart.reduce((s, c) => s + c.qty, 0);

function _highlight(text: string, query: string): string {
	if (!query.trim()) {
		return text;
	}
	const escaped = query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	return text.replace(new RegExp(`(${escaped})`, 'gi'), '<mark>$1</mark>');
}

function _doSearch() {
	if (searchQuery.trim()) {
		nav({ name: 'search', query: searchQuery.trim() });
	}
}

$: searchResults =
	current.name === 'search'
		? products.filter(
				(p) =>
					p.name.toLowerCase().includes(current.query.toLowerCase()) ||
					p.excerpt.toLowerCase().includes(current.query.toLowerCase()),
			)
		: [];

$: catalogProducts =
	current.name === 'catalog'
		? current.category
			? getByCategory(current.category as any)
			: products
		: [];

$: currentProduct =
	current.name === 'product' ? getProductBySku(current.sku) : null;
</script>

{#if !ready}
  <div style="display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:system-ui;color:#5a6e7a;background:#f0f2f4">Loading…</div>
{:else}
<div class="vm-shell">
  <!-- Header -->
  <header class="vm-header">
    <div class="vm-header-inner">
      <button class="vm-logo" on:click={() => nav({ name: 'home' })}>VaultMart</button>
      <form class="vm-search-form" on:submit|preventDefault={doSearch}>
        <input
          class="vm-search-input"
          bind:value={searchQuery}
          type="search"
          placeholder="Search products…"
        />
        <button class="vm-search-btn" type="submit">Search</button>
      </form>
      <button class="vm-cart-btn" on:click={() => nav({ name: 'cart' })}>
        Cart ({cartCount})
      </button>
    </div>
    <nav class="vm-nav">
      <button on:click={() => nav({ name: 'catalog' })}>All Products</button>
      {#each categories as cat}
        <button on:click={() => nav({ name: 'catalog', category: cat })}>{cat}</button>
      {/each}
    </nav>
  </header>

  <main class="vm-main">
    <!-- HOME -->
    {#if current.name === 'home'}
      <section class="vm-hero">
        <h1>Your fortress supply store</h1>
        <p>Mining tools, forge materials, food & more — delivered to any z-level.</p>
        <button class="vm-btn-cta" on:click={() => nav({ name: 'catalog' })}>Shop All Products</button>
      </section>
      <section class="vm-section">
        <h2 class="vm-section-title">Featured Products</h2>
        <div class="vm-product-grid">
          {#each getFeatured() as p}
            <div class="vm-product-card" data-sku={p.sku} data-category={p.category}>
              <img src={p.image} alt={p.name} />
              <div class="vm-card-body">
                <p class="vm-cat-label">{p.category}</p>
                <h3><button class="link-btn" on:click={() => nav({ name: 'product', sku: p.sku })}>{p.name}</button></h3>
                <p class="vm-excerpt">{p.excerpt}</p>
                <div class="vm-price-row">
                  {#if p.salePrice}
                    <span class="vm-price-sale">{formatPrice(p.salePrice)}</span>
                    <span class="vm-price-was">{formatPrice(p.basePrice)}</span>
                  {:else}
                    <span class="vm-price">{formatPrice(p.basePrice)}</span>
                  {/if}
                </div>
                <div class="vm-card-actions">
                  {#if p.inStock}
                    <button class="vm-btn-add" on:click={() => addToCart(p)}>Add to Cart</button>
                  {:else}
                    <button class="vm-btn-oos" disabled>Out of Stock</button>
                  {/if}
                </div>
              </div>
            </div>
          {/each}
        </div>
      </section>
      <section class="vm-section">
        <h2 class="vm-section-title">New Arrivals</h2>
        <div class="vm-product-grid">
          {#each getNew() as p}
            <div class="vm-product-card" data-sku={p.sku} data-category={p.category}>
              <img src={p.image} alt={p.name} />
              <div class="vm-card-body">
                <p class="vm-cat-label">{p.category}</p>
                <h3><button class="link-btn" on:click={() => nav({ name: 'product', sku: p.sku })}>{p.name}</button></h3>
                <div class="vm-price-row">
                  <span class="vm-price">{formatPrice(p.basePrice)}</span>
                </div>
                {#if p.inStock}
                  <button class="vm-btn-add" on:click={() => addToCart(p)}>Add to Cart</button>
                {:else}
                  <button class="vm-btn-oos" disabled>Out of Stock</button>
                {/if}
              </div>
            </div>
          {/each}
        </div>
      </section>

    <!-- CATALOG -->
    {:else if current.name === 'catalog'}
      <div class="vm-catalog-header">
        <h2>{current.category ?? 'All Products'}</h2>
        <div class="vm-cat-tabs">
          <button class="vm-cat-tab{!current.category ? ' active' : ''}" on:click={() => nav({ name: 'catalog' })}>All</button>
          {#each categories as cat}
            <button class="vm-cat-tab{current.category === cat ? ' active' : ''}" on:click={() => nav({ name: 'catalog', category: cat })}>{cat}</button>
          {/each}
        </div>
      </div>
      <div class="vm-product-grid">
        {#each catalogProducts as p}
          <div class="vm-product-card" data-sku={p.sku} data-category={p.category}>
            <img src={p.image} alt={p.name} />
            <div class="vm-card-body">
              <p class="vm-cat-label">{p.category}</p>
              {#if p.isNew}<span class="vm-badge-new">New</span>{/if}
              <h3><button class="link-btn" on:click={() => nav({ name: 'product', sku: p.sku })}>{p.name}</button></h3>
              <p class="vm-excerpt">{p.excerpt}</p>
              <div class="vm-rating">
                <span class="vm-stars">{'★'.repeat(Math.round(p.rating))}{'☆'.repeat(5 - Math.round(p.rating))}</span>
                <span class="vm-review-count">({p.reviewCount})</span>
              </div>
              <div class="vm-price-row">
                {#if p.salePrice}
                  <span class="vm-price-sale">{formatPrice(p.salePrice)}</span>
                  <span class="vm-price-was">{formatPrice(p.basePrice)}</span>
                {:else}
                  <span class="vm-price">{formatPrice(p.basePrice)}</span>
                {/if}
              </div>
              {#if p.inStock}
                <button class="vm-btn-add" on:click={() => addToCart(p)}>Add to Cart</button>
              {:else}
                <button class="vm-btn-oos" disabled>Out of Stock</button>
              {/if}
            </div>
          </div>
        {/each}
      </div>

    <!-- PRODUCT DETAIL -->
    {:else if current.name === 'product' && currentProduct}
      {@const p = currentProduct}
      <div class="vm-product-detail" data-sku={p.sku} data-category={p.category}>
        <div class="vm-detail-grid">
          <div class="vm-detail-image">
            <img src={p.image} alt={p.name} />
          </div>
          <div class="vm-detail-info">
            <p class="vm-cat-label">{p.category}</p>
            <h1 class="vm-detail-title">{p.name}</h1>
            <div class="vm-rating">
              <span class="vm-stars">{'★'.repeat(Math.round(p.rating))}{'☆'.repeat(5 - Math.round(p.rating))}</span>
              <span class="vm-review-count">({p.reviewCount} reviews)</span>
            </div>
            <p class="vm-detail-excerpt">{p.excerpt}</p>
            <div class="vm-price-row">
              {#if p.salePrice}
                <span class="vm-price-sale">{formatPrice(p.salePrice)}</span>
                <span class="vm-price-was">{formatPrice(p.basePrice)}</span>
              {:else}
                <span class="vm-price">{formatPrice(p.basePrice)}</span>
              {/if}
            </div>
            <div class="vm-variants">
              <label for="vm-material">Material</label>
              <select id="vm-material" name="material" disabled data-price-mod="0" data-in-stock="true">
                <option value="standard">Standard</option>
                <option value="masterwork">Masterwork (+20 GS)</option>
              </select>
              <label for="vm-qty">Quantity</label>
              <select id="vm-qty" name="quantity" disabled data-price-mod="0" data-in-stock="true">
                {#each [1,2,3,4,5] as n}
                  <option value={n}>{n}</option>
                {/each}
              </select>
            </div>
            {#if p.stock !== undefined}
              <p class="vm-stock-warn">Only {p.stock} left in stock</p>
            {/if}
            {#if p.inStock}
              <button class="vm-btn-add" on:click={() => addToCart(p)}>Add to Cart</button>
            {:else}
              <button class="vm-btn-oos" disabled>Out of Stock</button>
            {/if}
          </div>
        </div>
        <div class="vm-detail-nav">
          <button class="vm-btn-secondary" on:click={() => nav({ name: 'catalog' })}>← Back to Catalog</button>
        </div>
      </div>

    <!-- CART -->
    {:else if current.name === 'cart'}
      <div class="vm-cart" itemscope itemtype="https://schema.org/Order">
        <h2>Your Cart</h2>
        {#if cart.length === 0}
          <p class="vm-empty">Your cart is empty. <button class="link-btn" on:click={() => nav({ name: 'catalog' })}>Continue shopping</button></p>
        {:else}
          <table class="vm-cart-table">
            <thead>
              <tr><th>Product</th><th>Price</th><th>Qty</th><th>Subtotal</th><th></th></tr>
            </thead>
            <tbody>
              {#each cart as item}
                <tr itemprop="orderedItem" itemscope itemtype="https://schema.org/OrderItem">
                  <td itemprop="orderedItem">{item.name}</td>
                  <td itemprop="orderItemPrice">{formatPrice(item.price)}</td>
                  <td>
                    <input
                      class="vm-qty-input"
                      type="number"
                      min="0"
                      value={item.qty}
                      on:change={(e) => updateQty(item.sku, Number((e.target as HTMLInputElement).value))}
                    />
                  </td>
                  <td>{formatPrice(item.price * item.qty)}</td>
                  <td><button class="vm-remove-btn" on:click={() => updateQty(item.sku, 0)}>Remove</button></td>
                </tr>
              {/each}
            </tbody>
          </table>
          <div class="vm-cart-total">
            <span>Total:</span>
            <strong itemprop="price">{formatPrice(cartTotal)}</strong>
          </div>
          <button class="vm-btn-cta">Proceed to Checkout</button>
        {/if}
      </div>

    <!-- SEARCH RESULTS -->
    {:else if current.name === 'search'}
      <div class="vm-search-results">
        <h2>Search results for "{current.query}"</h2>
        <p class="vm-result-count">{searchResults.length} product{searchResults.length !== 1 ? 's' : ''} found</p>
        <div class="vm-product-grid">
          {#each searchResults as p}
            <div class="vm-product-card" data-sku={p.sku} data-category={p.category}>
              <img src={p.image} alt={p.name} />
              <div class="vm-card-body">
                <p class="vm-cat-label">{p.category}</p>
                <h3><button class="link-btn" on:click={() => nav({ name: 'product', sku: p.sku })}>
                  <!-- svelte-ignore a11y-no-static-element-interactions -->
                  {@html highlight(p.name, current.query)}
                </button></h3>
                <p class="vm-excerpt">{@html highlight(p.excerpt, current.query)}</p>
                <div class="vm-price-row">
                  {#if p.salePrice}
                    <span class="vm-price-sale">{formatPrice(p.salePrice)}</span>
                    <span class="vm-price-was">{formatPrice(p.basePrice)}</span>
                  {:else}
                    <span class="vm-price">{formatPrice(p.basePrice)}</span>
                  {/if}
                </div>
                {#if p.inStock}
                  <button class="vm-btn-add" on:click={() => addToCart(p)}>Add to Cart</button>
                {:else}
                  <button class="vm-btn-oos" disabled>Out of Stock</button>
                {/if}
              </div>
            </div>
          {/each}
        </div>
      </div>
    {/if}
  </main>

  <footer class="vm-footer">
    <p>© Year 312 VaultMart · All fortress levels served · Trading Post Z-Level 8</p>
  </footer>
</div>
{/if}

<style>
  .vm-shell { min-height: 100vh; display: flex; flex-direction: column; }

  /* Header */
  .vm-header { background: var(--vm-surface); border-bottom: 1px solid var(--vm-border); position: sticky; top: 0; z-index: 100; }
  .vm-header-inner { max-width: 1200px; margin: 0 auto; padding: 12px 24px; display: flex; align-items: center; gap: 16px; }
  .vm-logo { background: none; border: none; color: var(--vm-primary); font-family: var(--vm-font); font-size: 1.5rem; font-weight: 700; cursor: pointer; }
  .vm-search-form { flex: 1; display: flex; gap: 6px; }
  .vm-search-input { flex: 1; padding: 8px 12px; border: 1px solid var(--vm-border); border-radius: var(--vm-radius); font-family: var(--vm-font); font-size: 14px; }
  .vm-search-btn { background: var(--vm-primary); color: #fff; border: none; padding: 8px 16px; border-radius: var(--vm-radius); font-family: var(--vm-font); font-size: 14px; cursor: pointer; }
  .vm-cart-btn { background: var(--vm-cta); color: #fff; border: none; padding: 8px 18px; border-radius: var(--vm-radius); font-family: var(--vm-font); font-size: 14px; font-weight: 600; cursor: pointer; white-space: nowrap; }
  .vm-nav { max-width: 1200px; margin: 0 auto; padding: 6px 24px; display: flex; flex-wrap: wrap; gap: 4px; }
  .vm-nav button { background: none; border: none; color: var(--vm-muted); font-family: var(--vm-font); font-size: 13px; padding: 4px 12px; cursor: pointer; border-radius: 20px; }
  .vm-nav button:hover { background: var(--vm-bg); color: var(--vm-text); }

  /* Main */
  .vm-main { flex: 1; max-width: 1200px; margin: 0 auto; width: 100%; padding: 32px 24px; }

  /* Hero */
  .vm-hero { background: var(--vm-primary); color: #fff; border-radius: var(--vm-radius); padding: 40px 32px; text-align: center; margin-bottom: 40px; }
  .vm-hero h1 { font-size: 2rem; font-weight: 700; margin-bottom: 8px; }
  .vm-hero p { font-size: 1.1rem; opacity: 0.85; margin-bottom: 20px; }

  /* Section */
  .vm-section { margin-bottom: 40px; }
  .vm-section-title { font-size: 1.4rem; font-weight: 700; margin-bottom: 20px; }

  /* Product grid */
  .vm-product-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 20px; }
  .vm-product-card { background: var(--vm-surface); border: 1px solid var(--vm-border); border-radius: var(--vm-radius); overflow: hidden; }
  .vm-card-body { padding: 14px; }
  .vm-cat-label { font-size: 11px; color: var(--vm-muted); text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 4px; }
  .vm-card-body h3, .vm-detail-title { font-size: 1rem; font-weight: 600; margin-bottom: 6px; }
  .link-btn { background: none; border: none; color: inherit; font-family: inherit; font-size: inherit; font-weight: inherit; cursor: pointer; text-align: left; padding: 0; }
  .link-btn:hover { color: var(--vm-primary); }
  .vm-excerpt { font-size: 13px; color: var(--vm-muted); margin-bottom: 8px; line-height: 1.5; }
  .vm-badge-new { font-size: 10px; font-weight: 700; background: var(--vm-cta); color: #fff; padding: 1px 6px; border-radius: 2px; text-transform: uppercase; letter-spacing: 0.06em; display: inline-block; margin-bottom: 4px; }
  .vm-rating { display: flex; align-items: center; gap: 4px; margin-bottom: 6px; }
  .vm-stars { color: #f59e0b; font-size: 13px; }
  .vm-review-count { font-size: 12px; color: var(--vm-muted); }
  .vm-price-row { display: flex; align-items: baseline; gap: 8px; margin-bottom: 10px; }
  .vm-price { font-size: 1.1rem; font-weight: 700; color: var(--vm-text); }
  .vm-price-sale { font-size: 1.1rem; font-weight: 700; color: var(--vm-cta); }
  .vm-price-was { font-size: 13px; text-decoration: line-through; color: var(--vm-muted); }
  .vm-btn-add { background: var(--vm-cta); color: #fff; border: none; padding: 8px 16px; border-radius: var(--vm-radius); font-family: var(--vm-font); font-size: 13px; font-weight: 600; cursor: pointer; width: 100%; }
  .vm-btn-add:hover { background: var(--vm-cta-hover); }
  .vm-btn-oos { background: var(--vm-border); color: var(--vm-muted); border: none; padding: 8px 16px; border-radius: var(--vm-radius); font-family: var(--vm-font); font-size: 13px; cursor: not-allowed; width: 100%; }
  .vm-btn-cta { background: var(--vm-cta); color: #fff; border: none; padding: 12px 28px; border-radius: var(--vm-radius); font-family: var(--vm-font); font-size: 15px; font-weight: 700; cursor: pointer; }
  .vm-btn-cta:hover { background: var(--vm-cta-hover); }
  .vm-btn-secondary { background: none; border: 1px solid var(--vm-border); color: var(--vm-text); padding: 8px 18px; border-radius: var(--vm-radius); font-family: var(--vm-font); font-size: 14px; cursor: pointer; }

  /* Catalog header */
  .vm-catalog-header { margin-bottom: 24px; }
  .vm-catalog-header h2 { font-size: 1.6rem; font-weight: 700; margin-bottom: 12px; }
  .vm-cat-tabs { display: flex; flex-wrap: wrap; gap: 8px; }
  .vm-cat-tab { background: var(--vm-surface); border: 1px solid var(--vm-border); padding: 5px 14px; font-family: var(--vm-font); font-size: 13px; cursor: pointer; border-radius: 20px; color: var(--vm-muted); }
  .vm-cat-tab:hover, .vm-cat-tab.active { background: var(--vm-primary); border-color: var(--vm-primary); color: #fff; }

  /* Product detail */
  .vm-product-detail { max-width: 960px; }
  .vm-detail-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 40px; margin-bottom: 32px; }
  .vm-detail-image img { width: 100%; border-radius: var(--vm-radius); }
  .vm-detail-title { font-size: 1.6rem; font-weight: 700; margin-bottom: 8px; }
  .vm-detail-excerpt { font-size: 15px; line-height: 1.6; margin-bottom: 16px; }
  .vm-variants { display: flex; flex-direction: column; gap: 6px; margin: 16px 0; }
  .vm-variants label { font-size: 13px; font-weight: 600; color: var(--vm-muted); }
  .vm-variants select { padding: 7px 10px; border: 1px solid var(--vm-border); border-radius: var(--vm-radius); font-family: var(--vm-font); font-size: 14px; background: var(--vm-surface); }
  .vm-stock-warn { font-size: 13px; color: #ef4444; margin-bottom: 8px; }
  .vm-detail-nav { margin-top: 24px; }

  /* Cart */
  .vm-cart h2 { font-size: 1.6rem; font-weight: 700; margin-bottom: 20px; }
  .vm-empty { font-size: 15px; color: var(--vm-muted); }
  .vm-cart-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  .vm-cart-table th { text-align: left; font-size: 13px; color: var(--vm-muted); padding: 8px 12px; border-bottom: 2px solid var(--vm-border); }
  .vm-cart-table td { padding: 12px; border-bottom: 1px solid var(--vm-border); font-size: 15px; }
  .vm-qty-input { width: 60px; padding: 4px 8px; border: 1px solid var(--vm-border); border-radius: var(--vm-radius); font-size: 14px; }
  .vm-remove-btn { background: none; border: none; color: #ef4444; font-size: 13px; cursor: pointer; }
  .vm-cart-total { text-align: right; font-size: 1.2rem; margin-bottom: 20px; display: flex; justify-content: flex-end; gap: 12px; }

  /* Search */
  .vm-search-results h2 { font-size: 1.4rem; font-weight: 700; margin-bottom: 4px; }
  .vm-result-count { font-size: 13px; color: var(--vm-muted); margin-bottom: 20px; }
  :global(mark) { background: #fef08a; color: inherit; border-radius: 2px; padding: 0 1px; }

  /* Footer */
  .vm-footer { background: var(--vm-surface); border-top: 1px solid var(--vm-border); text-align: center; padding: 20px 24px; font-size: 13px; color: var(--vm-muted); }
</style>

// src/components/l2/solid/eshop/EshopApp.tsx
/**
 * @qscrape L2 / solid / eshop
 * @component EshopApp
 */

import type { JSX } from 'solid-js';
import {
	createSignal,
	For,
	Match,
	onCleanup,
	onMount,
	Show,
	Switch,
} from 'solid-js';
import { fakeGet } from '../../../../data/api';
import type { ProductMeta } from '../../../../data/eshop/products';
import {
	categories,
	getByCategory,
	getFeatured,
	getNew,
	getProductBySku,
	products,
} from '../../../../data/eshop/products';
import '../../../../styles/l2/eshop.css';
import styles from '../../react/eshop/EshopApp.module.css';

// ── URL routing helpers ──────────────────────────────────────────────────────

function getBase(): string {
	return `/${window.location.pathname.split('/').filter(Boolean).slice(0, 3).join('/')}/`;
}

function pathToState(): {
	page: Page;
	sku?: string;
	query?: string;
	category?: string;
} {
	const seg = window.location.pathname.split('/').filter(Boolean).at(-1) ?? '';
	const p = new URLSearchParams(window.location.search);
	if (seg === 'product') {
		return { page: 'product', sku: p.get('sku') ?? undefined };
	}
	if (seg === 'catalog') {
		return { page: 'catalog', category: p.get('cat') ?? undefined };
	}
	if (seg === 'cart') {
		return { page: 'cart' };
	}
	if (seg === 'search') {
		return { page: 'search', query: p.get('q') ?? '' };
	}
	return { page: 'home' };
}

function pageToPath(p: Page, extra?: string): string {
	const base = getBase();
	if (p === 'product') {
		return `${base}product${extra ? `?sku=${extra}` : ''}`;
	}
	if (p === 'catalog') {
		return `${base}catalog${extra ? `?cat=${encodeURIComponent(extra)}` : ''}`;
	}
	if (p === 'cart') {
		return `${base}cart`;
	}
	if (p === 'search') {
		return `${base}search${extra ? `?q=${encodeURIComponent(extra)}` : ''}`;
	}
	return base;
}

type Page = 'home' | 'catalog' | 'product' | 'cart' | 'search';

interface CartItem {
	sku: string;
	qty: number;
}

function StarRating(props: { rating: number; reviewCount: number }) {
	const full = () => Math.floor(props.rating);
	const half = () => props.rating - full() >= 0.5;
	const empty = () => 5 - full() - (half() ? 1 : 0);
	return (
		<span class={styles.stars}>
			{'★'.repeat(full())}
			{half() ? '½' : ''}
			{'☆'.repeat(empty())}
			<span class={styles.reviewCount}>({props.reviewCount})</span>
		</span>
	);
}

function PriceDisplay(props: { product: ProductMeta }) {
	return (
		<Show
			when={props.product.salePrice}
			fallback={
				<span class={styles.price}>
					{props.product.basePrice.toFixed(2)} GS
				</span>
			}
		>
			<span class={styles.priceWrap}>
				<span class={styles.salePrice}>
					{props.product.salePrice!.toFixed(2)} GS
				</span>
				<span class={styles.origPrice}>
					{props.product.basePrice.toFixed(2)} GS
				</span>
			</span>
		</Show>
	);
}

function CategoryBadge(props: { category: string }) {
	const slug = () => props.category.toLowerCase().replace(/[^a-z]/g, '_');
	return (
		<span class={`${styles.catBadge} ${styles[`cat_${slug()}`]}`}>
			{props.category}
		</span>
	);
}

function ProductCard(props: {
	product: ProductMeta;
	onNavigate: (page: Page, sku?: string) => void;
}) {
	return (
		<article
			class={styles.productCard}
			data-sku={props.product.sku}
			data-category={props.product.category}
		>
			<a
				class={styles.productCardImg}
				onClick={() => props.onNavigate('product', props.product.sku)}
			>
				<img
					src={props.product.image}
					alt={props.product.name}
					loading="lazy"
					width="280"
					height="200"
				/>
				<div class={styles.productBadges}>
					<Show when={props.product.isNew}>
						<span class={styles.badgeNew}>NEW</span>
					</Show>
					<Show when={!props.product.inStock}>
						<span class={styles.badgeOos}>OUT OF STOCK</span>
					</Show>
					<Show when={props.product.salePrice}>
						<span class={styles.badgeSale}>SALE</span>
					</Show>
				</div>
			</a>
			<div class={styles.productCardBody}>
				<CategoryBadge category={props.product.category} />
				<h3 class={styles.productName}>
					<a onClick={() => props.onNavigate('product', props.product.sku)}>
						{props.product.name}
					</a>
				</h3>
				<StarRating
					rating={props.product.rating}
					reviewCount={props.product.reviewCount}
				/>
				<div class={styles.productCardFooter}>
					<PriceDisplay product={props.product} />
					<Show
						when={props.product.inStock}
						fallback={<span class={styles.oosLabel}>Out of Stock</span>}
					>
						<button
							type="button"
							class={styles.addBtn}
							onClick={() => props.onNavigate('cart')}
						>
							Add to Cart
						</button>
					</Show>
				</div>
			</div>
		</article>
	);
}

function EshopShell(props: {
	children: JSX.Element;
	activePage: Page;
	onNavigate: (page: Page, extra?: string) => void;
	cartCount: number;
}) {
	const [searchQ, setSearchQ] = createSignal('');

	return (
		<div class={styles.shell}>
			<header class={styles.header}>
				<div class={styles.headerInner}>
					<button
						type="button"
						class={styles.logo}
						onClick={() => props.onNavigate('home')}
					>
						VaultMart
					</button>
					<form
						class={styles.searchBar}
						onSubmit={(e) => {
							e.preventDefault();
							props.onNavigate('search', searchQ());
						}}
					>
						<input
							type="search"
							class={styles.searchInput}
							placeholder="Search products…"
							value={searchQ()}
							onInput={(e) => setSearchQ(e.currentTarget.value)}
						/>
						<button type="submit" class={styles.searchBtn}>
							Search
						</button>
					</form>
					<button
						type="button"
						class={styles.cartBtn}
						onClick={() => props.onNavigate('cart')}
					>
						Cart{' '}
						<Show when={props.cartCount > 0}>
							<span class={styles.cartBadge}>{props.cartCount}</span>
						</Show>
					</button>
				</div>
				<nav class={styles.catNav}>
					<div class={styles.catNavInner}>
						<button
							type="button"
							class={`${styles.catNavItem} ${props.activePage === 'home' ? styles.catNavActive : ''}`}
							onClick={() => props.onNavigate('home')}
						>
							Home
						</button>
						<For each={categories}>
							{(cat) => (
								<button
									type="button"
									class={styles.catNavItem}
									onClick={() => props.onNavigate('catalog')}
								>
									{cat}
								</button>
							)}
						</For>
						<button
							type="button"
							class={`${styles.catNavItem} ${props.activePage === 'catalog' ? styles.catNavActive : ''}`}
							onClick={() => props.onNavigate('catalog')}
						>
							All Products
						</button>
					</div>
				</nav>
			</header>
			<main class={styles.main}>{props.children}</main>
			<footer class={styles.footer}>
				<div class={styles.footerInner}>
					<p>&copy; Year 312 VaultMart. A division of Armok Holdings LLC.</p>
					<p class={styles.footerMuted}>
						All prices in Gold Sovereigns (GS). Copper Coins (CC) accepted at
						1:100 rate.
					</p>
				</div>
			</footer>
		</div>
	);
}

function HomePage(props: { onNavigate: (page: Page, extra?: string) => void }) {
	const featured = getFeatured();
	const newArrivals = getNew();

	return (
		<div class={styles.homePage}>
			<section class={styles.heroBanner}>
				<div class={styles.heroBannerText}>
					<p class={styles.heroBannerSub}>Welcome to</p>
					<h1 class={styles.heroBannerTitle}>VaultMart</h1>
					<p class={styles.heroBannerDesc}>
						Your trusted supplier for mining equipment, forge materials, and
						surface imports. Serving Mountainhome since Year 89.
					</p>
					<button
						type="button"
						class={styles.heroCta}
						onClick={() => props.onNavigate('catalog')}
					>
						Shop All Products →
					</button>
				</div>
			</section>
			<section class={styles.section}>
				<h2 class={styles.sectionTitle}>Browse by Category</h2>
				<div class={styles.catTiles}>
					<For each={categories}>
						{(cat) => (
							<button
								type="button"
								class={styles.catTile}
								onClick={() => props.onNavigate('catalog')}
								data-category={cat}
							>
								<span class={styles.catTileName}>{cat}</span>
								<span class={styles.catTileCount}>
									{getByCategory(cat).length} items
								</span>
							</button>
						)}
					</For>
				</div>
			</section>
			<section class={styles.section}>
				<h2 class={styles.sectionTitle}>Featured Products</h2>
				<div class={styles.grid3}>
					<For each={featured}>
						{(p) => <ProductCard product={p} onNavigate={props.onNavigate} />}
					</For>
				</div>
			</section>
			<section class={styles.section}>
				<h2 class={styles.sectionTitle}>New Arrivals</h2>
				<div class={styles.grid3}>
					<For each={newArrivals.slice(0, 6)}>
						{(p) => <ProductCard product={p} onNavigate={props.onNavigate} />}
					</For>
				</div>
				<button
					type="button"
					class={styles.viewAllBtn}
					onClick={() => props.onNavigate('catalog')}
				>
					View All Products →
				</button>
			</section>
		</div>
	);
}

function CatalogPage(props: {
	onNavigate: (page: Page, extra?: string) => void;
}) {
	const [activeCategory, setActiveCategory] = createSignal('All');
	const [page, setPage] = createSignal(1);
	const PER_PAGE = 9;

	const filtered = () =>
		activeCategory() === 'All' ? products : getByCategory(activeCategory());
	const totalPages = () => Math.ceil(filtered().length / PER_PAGE);
	const pageItems = () =>
		filtered().slice((page() - 1) * PER_PAGE, page() * PER_PAGE);

	return (
		<div class={styles.catalogPage}>
			<h1 class={styles.pageTitle}>All Products</h1>
			<div class={styles.catalogLayout}>
				<aside class={styles.filterRail}>
					<h3 class={styles.filterTitle}>Category</h3>
					<button
						type="button"
						class={`${styles.filterItem} ${activeCategory() === 'All' ? styles.filterItemActive : ''}`}
						onClick={() => {
							setActiveCategory('All');
							setPage(1);
						}}
					>
						All ({products.length})
					</button>
					<For each={categories}>
						{(cat) => (
							<button
								type="button"
								class={`${styles.filterItem} ${activeCategory() === cat ? styles.filterItemActive : ''}`}
								onClick={() => {
									setActiveCategory(cat);
									setPage(1);
								}}
								data-category={cat}
							>
								{cat} ({getByCategory(cat).length})
							</button>
						)}
					</For>
				</aside>
				<div class={styles.catalogMain}>
					<div class={styles.catalogMeta}>
						<span>{filtered().length} products</span>
					</div>
					<div class={styles.grid3}>
						<For each={pageItems()}>
							{(p) => <ProductCard product={p} onNavigate={props.onNavigate} />}
						</For>
					</div>
					<Show when={totalPages() > 1}>
						<div class={styles.pagination}>
							<For each={Array.from({ length: totalPages() }, (_, i) => i + 1)}>
								{(p) => (
									<button
										type="button"
										class={`${styles.pageBtn} ${p === page() ? styles.pageBtnActive : ''}`}
										onClick={() => setPage(p)}
									>
										{p}
									</button>
								)}
							</For>
						</div>
					</Show>
				</div>
			</div>
		</div>
	);
}

function ProductPage(props: {
	sku: string;
	onNavigate: (page: Page, extra?: string) => void;
	onAddToCart: (sku: string) => void;
}) {
	const product = () => getProductBySku(props.sku);
	const [qty, setQty] = createSignal(1);

	const related = () =>
		product()
			? getByCategory(product()!.category)
					.filter((p) => p.sku !== props.sku)
					.slice(0, 3)
			: [];

	return (
		<Show
			when={product()}
			fallback={
				<div class={styles.notFound}>
					<h1>Product not found</h1>
					<button type="button" onClick={() => props.onNavigate('catalog')}>
						← Back to Catalog
					</button>
				</div>
			}
		>
			{(prod) => (
				<div class={styles.productPage}>
					<nav class={styles.breadcrumb}>
						<button type="button" onClick={() => props.onNavigate('home')}>
							Home
						</button>
						{' / '}
						<button type="button" onClick={() => props.onNavigate('catalog')}>
							{prod().category}
						</button>
						{' / '}
						<span>{prod().name}</span>
					</nav>
					<div class={styles.productDetail}>
						<div class={styles.productDetailImg}>
							<img
								src={prod().image}
								alt={prod().name}
								width="560"
								height="400"
							/>
							<div class={styles.productBadges}>
								<Show when={prod().isNew}>
									<span class={styles.badgeNew}>NEW</span>
								</Show>
								<Show when={!prod().inStock}>
									<span class={styles.badgeOos}>OUT OF STOCK</span>
								</Show>
								<Show when={prod().salePrice}>
									<span class={styles.badgeSale}>SALE</span>
								</Show>
							</div>
						</div>
						<div class={styles.productDetailInfo}>
							<CategoryBadge category={prod().category} />
							<h1 class={styles.productDetailName}>{prod().name}</h1>
							<div class={styles.productDetailMeta}>
								<StarRating
									rating={prod().rating}
									reviewCount={prod().reviewCount}
								/>
								<span class={styles.skuLabel}>SKU: {prod().sku}</span>
							</div>
							<div class={styles.productDetailPrice}>
								<PriceDisplay product={prod()} />
							</div>
							<p class={styles.productDetailExcerpt}>{prod().excerpt}</p>
							<Show
								when={
									prod().stock && prod().inStock && (prod().stock ?? 0) <= 5
								}
							>
								<p class={styles.lowStock}>
									Only {prod().stock} left in stock!
								</p>
							</Show>
							<Show
								when={prod().inStock}
								fallback={<p class={styles.outOfStock}>Out of Stock</p>}
							>
								<div class={styles.addToCartRow}>
									<div class={styles.qtyControl}>
										<button
											type="button"
											onClick={() => setQty(Math.max(1, qty() - 1))}
										>
											−
										</button>
										<span data-qty={qty()}>{qty()}</span>
										<button type="button" onClick={() => setQty(qty() + 1)}>
											+
										</button>
									</div>
									<button
										type="button"
										class={styles.addToCartBtn}
										onClick={() => {
											props.onAddToCart(prod().sku);
											props.onNavigate('cart');
										}}
									>
										Add to Cart
									</button>
								</div>
							</Show>
							<div class={styles.variantSelects}>
								<div class={styles.variantGroup}>
									<label>Material</label>
									<select disabled>
										<option data-price-mod="0" data-in-stock="true">
											Standard
										</option>
										<option data-price-mod="10" data-in-stock="true">
											Masterwork (+10 GS)
										</option>
										<option data-price-mod="25" data-in-stock="false">
											Legendary (+25 GS, Out of Stock)
										</option>
									</select>
								</div>
								<div class={styles.variantGroup}>
									<label>Size</label>
									<select disabled>
										<option data-price-mod="0" data-in-stock="true">
											Standard
										</option>
										<option data-price-mod="5" data-in-stock="true">
											Large (+5 GS)
										</option>
									</select>
								</div>
							</div>
						</div>
					</div>
					<Show when={related().length > 0}>
						<section class={styles.relatedSection}>
							<h2 class={styles.sectionTitle}>Related Products</h2>
							<div class={styles.grid3}>
								<For each={related()}>
									{(p) => (
										<ProductCard product={p} onNavigate={props.onNavigate} />
									)}
								</For>
							</div>
						</section>
					</Show>
				</div>
			)}
		</Show>
	);
}

function CartPage(props: {
	cart: CartItem[];
	onNavigate: (page: Page, extra?: string) => void;
}) {
	const items = () =>
		props.cart
			.map((ci) => ({ ...ci, product: getProductBySku(ci.sku) }))
			.filter((ci) => ci.product);

	const displayItems = () => {
		const it = items();
		if (it.length > 0) {
			return it;
		}
		return [
			{ sku: 'VM-MIN-001', qty: 2, product: getProductBySku('VM-MIN-001') },
			{ sku: 'VM-FDB-002', qty: 1, product: getProductBySku('VM-FDB-002') },
			{ sku: 'VM-SRF-001', qty: 1, product: getProductBySku('VM-SRF-001') },
		].filter((ci) => ci.product);
	};

	const displaySubtotal = () =>
		displayItems().reduce((sum, ci) => {
			const p = ci.product!;
			return sum + (p.salePrice || p.basePrice) * ci.qty;
		}, 0);
	const displayTotal = () => displaySubtotal() + 3.5;

	const ldJson = () =>
		JSON.stringify({
			'@context': 'https://schema.org',
			'@type': 'Order',
			orderStatus: 'OrderProcessing',
			priceCurrency: 'GS',
			price: displayTotal().toFixed(2),
			orderedItem: displayItems().map((ci) => ({
				'@type': 'OrderItem',
				orderQuantity: ci.qty,
				orderedItem: {
					'@type': 'Product',
					name: ci.product!.name,
					sku: ci.sku,
				},
				orderItemPrice: {
					'@type': 'PriceSpecification',
					price: (
						(ci.product!.salePrice || ci.product!.basePrice) * ci.qty
					).toFixed(2),
				},
			})),
		});

	return (
		<div class={styles.cartPage}>
			<h1 class={styles.pageTitle}>Your Cart</h1>
			<script type="application/ld+json" innerHTML={ldJson()} />
			<div class={styles.cartLayout}>
				<div class={styles.cartItems}>
					<For each={displayItems()}>
						{(ci) => (
							<div class={styles.cartItem}>
								<img
									src={ci.product!.image}
									alt={ci.product!.name}
									width="80"
									height="60"
								/>
								<div class={styles.cartItemInfo}>
									<a
										class={styles.cartItemName}
										onClick={() => props.onNavigate('product', ci.sku)}
									>
										{ci.product!.name}
									</a>
									<div class={styles.cartItemMeta}>
										SKU: {ci.sku} · Qty: {ci.qty}
									</div>
								</div>
								<div class={styles.cartItemPrice}>
									{(
										(ci.product!.salePrice || ci.product!.basePrice) * ci.qty
									).toFixed(2)}{' '}
									GS
								</div>
							</div>
						)}
					</For>
				</div>
				<div class={styles.cartSummary}>
					<h2 class={styles.summaryTitle}>Order Summary</h2>
					<div class={styles.summaryRow}>
						<span>Subtotal</span>
						<span>{displaySubtotal().toFixed(2)} GS</span>
					</div>
					<div class={styles.summaryRow}>
						<span>Shipping</span>
						<span>3.50 GS</span>
					</div>
					<div class={`${styles.summaryRow} ${styles.summaryTotal}`}>
						<span>Total</span>
						<span>{displayTotal().toFixed(2)} GS</span>
					</div>
					<button type="button" class={styles.checkoutBtn}>
						Proceed to Checkout
					</button>
					<button
						type="button"
						class={styles.continueBtn}
						onClick={() => props.onNavigate('catalog')}
					>
						Continue Shopping
					</button>
				</div>
			</div>
		</div>
	);
}

function SearchPage(props: {
	query: string;
	onNavigate: (page: Page, extra?: string) => void;
}) {
	const q = () => props.query.toLowerCase();
	const results = () =>
		q()
			? products.filter(
					(p) =>
						p.name.toLowerCase().includes(q()) ||
						p.excerpt.toLowerCase().includes(q()),
				)
			: [];

	function highlight(text: string): JSX.Element {
		if (!q()) {
			return <>{text}</>;
		}
		const parts = text.split(new RegExp(`(${q()})`, 'gi'));
		return (
			<>
				{parts.map((part) =>
					// biome-ignore lint/correctness/useJsxKeyInIterable: Solid does not use React key prop
					part.toLowerCase() === q() ? <mark>{part}</mark> : part,
				)}
			</>
		);
	}

	return (
		<div class={styles.searchPage}>
			<h1 class={styles.pageTitle}>
				Search Results{' '}
				<Show when={props.query}>
					<span class={styles.searchQuery}>
						for &ldquo;{props.query}&rdquo;
					</span>
				</Show>
			</h1>
			<Show
				when={results().length === 0}
				fallback={
					<div class={styles.searchResults}>
						<p class={styles.searchCount}>
							{results().length} product{results().length !== 1 ? 's' : ''}{' '}
							found
						</p>
						<For each={results()}>
							{(p) => (
								<div class={styles.searchResultItem} data-sku={p.sku}>
									<img src={p.image} alt={p.name} width="100" height="75" />
									<div class={styles.searchResultInfo}>
										<a
											class={styles.searchResultName}
											onClick={() => props.onNavigate('product', p.sku)}
										>
											{highlight(p.name)}
										</a>
										<p class={styles.searchResultExcerpt}>
											{highlight(p.excerpt)}
										</p>
									</div>
									<span class={styles.searchResultPrice}>
										{(p.salePrice || p.basePrice).toFixed(2)} GS
									</span>
								</div>
							)}
						</For>
					</div>
				}
			>
				<p class={styles.noResults}>
					{props.query ? 'No products found.' : 'Enter a search term above.'}
				</p>
			</Show>
		</div>
	);
}

export default function EshopApp(props: {
	initialPage?: Page;
	initialSku?: string;
}) {
	const [ready, setReady] = createSignal(false);
	const [page, setPage] = createSignal<Page>(props.initialPage || 'home');
	const [sku, setSku] = createSignal<string | undefined>(props.initialSku);
	const [searchQuery, setSearchQuery] = createSignal('');
	const [cart, setCart] = createSignal<CartItem[]>([]);

	onMount(() => {
		const s = pathToState();
		setPage(s.page);
		if (s.sku) {
			setSku(s.sku);
		}
		if (s.query) {
			setSearchQuery(s.query);
		}

		fakeGet(null).then(() => setReady(true));

		const onPop = () => {
			const st = pathToState();
			setPage(st.page);
			if (st.sku) {
				setSku(st.sku);
			}
			if (st.query != null) {
				setSearchQuery(st.query);
			}
			window.scrollTo(0, 0);
		};
		window.addEventListener('popstate', onPop);
		onCleanup(() => window.removeEventListener('popstate', onPop));
	});

	const navigate = (p: Page, extra?: string) => {
		setPage(p);
		if (p === 'product' && extra) {
			setSku(extra);
		}
		if (p === 'search' && extra) {
			setSearchQuery(extra);
		}
		history.pushState(null, '', pageToPath(p, extra));
		window.scrollTo(0, 0);
	};

	const addToCart = (itemSku: string) => {
		setCart((prev) => {
			const existing = prev.find((i) => i.sku === itemSku);
			if (existing) {
				return prev.map((i) =>
					i.sku === itemSku ? { ...i, qty: i.qty + 1 } : i,
				);
			}
			return [...prev, { sku: itemSku, qty: 1 }];
		});
	};

	const cartCount = () => cart().reduce((sum, i) => sum + i.qty, 0);

	return (
		<Show
			when={ready()}
			fallback={
				<div
					style={{
						display: 'flex',
						'align-items': 'center',
						'justify-content': 'center',
						'min-height': '100vh',
						'font-family': 'system-ui',
						color: '#888',
					}}
				>
					Loading…
				</div>
			}
		>
			<EshopShell
				activePage={page()}
				onNavigate={navigate}
				cartCount={cartCount()}
			>
				<Switch>
					<Match when={page() === 'home'}>
						<HomePage onNavigate={navigate} />
					</Match>
					<Match when={page() === 'catalog'}>
						<CatalogPage onNavigate={navigate} />
					</Match>
					<Match when={page() === 'product'}>
						<ProductPage
							sku={sku() || ''}
							onNavigate={navigate}
							onAddToCart={addToCart}
						/>
					</Match>
					<Match when={page() === 'cart'}>
						<CartPage cart={cart()} onNavigate={navigate} />
					</Match>
					<Match when={page() === 'search'}>
						<SearchPage query={searchQuery()} onNavigate={navigate} />
					</Match>
					<Match when={true}>
						<HomePage onNavigate={navigate} />
					</Match>
				</Switch>
			</EshopShell>
		</Show>
	);
}
