// src/components/l2/taxes/vue/TaxesApp.vue
<!-- @qscrape L2 / vue / taxes -->
<!-- @component TaxesApp -->
<template>
  <div v-if="!ready" style="display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:'IBM Plex Sans',system-ui;color:#6c757d;background:#f8f9fa">Loading…</div>
  <div v-else class="er-shell">
    <header class="er-header">
      <div class="er-header-top">
        <div class="er-header-inner">
          <div class="er-brand">
            <div class="er-crest">⚒</div>
            <div>
              <div class="er-title">Eldoria Registry of Deeds</div>
              <div class="er-sub">Granite Flats County · Official Records System</div>
            </div>
          </div>
          <div class="er-meta">
            <div>Year 312 Record System</div>
            <div class="er-version">Version 4.2.1</div>
          </div>
        </div>
      </div>
      <nav class="er-nav">
        <div class="er-nav-inner">
          <button v-for="p in navPages" :key="p.id"
            :class="['er-nav-item', { 'er-nav-item--active': page === p.id }]"
            @click="navigate(p.id)">{{ p.label }}</button>
        </div>
      </nav>
    </header>

    <!-- Home -->
    <main class="er-main" v-if="page === 'home'">
      <div class="er-hero">
        <h1 class="er-hero-title">Eldoria Registry of Deeds</h1>
        <p class="er-hero-sub">Official real property records for Granite Flats County.</p>
        <button class="er-hero-btn" @click="navigate('search')">Search Records →</button>
      </div>
      <div class="er-home-grid">
        <div class="er-home-card">
          <div class="er-home-icon">🔍</div>
          <h2 class="er-home-card-title">Search Records</h2>
          <p class="er-home-card-desc">Search by party name, date range, or instrument type. Full text search across all {{ deeds.length }} recorded instruments.</p>
          <button class="er-home-card-btn" @click="navigate('search')">Go to Search</button>
        </div>
        <div class="er-home-card">
          <div class="er-home-icon">📄</div>
          <h2 class="er-home-card-title">How-To Guides</h2>
          <p class="er-home-card-desc">Step-by-step guides for interpreting each instrument type.</p>
          <button class="er-home-card-btn" @click="navigate('howto')">View Guides</button>
        </div>
        <div class="er-home-card">
          <div class="er-home-icon">💰</div>
          <h2 class="er-home-card-title">Recording Fees</h2>
          <p class="er-home-card-desc">Current fee schedule for recording new instruments. Updated Year 312.</p>
          <button class="er-home-card-btn" @click="navigate('fees')">View Fees</button>
        </div>
      </div>
      <div class="er-office-hours">
        <h2 class="er-oh-title">Office Hours</h2>
        <table class="er-oh-table">
          <tbody>
            <tr><td>Monday – Friday</td><td>08:00 – 17:00</td></tr>
            <tr><td>Saturday</td><td>09:00 – 13:00</td></tr>
            <tr><td>Sunday</td><td>Closed</td></tr>
          </tbody>
        </table>
      </div>
    </main>

    <!-- Search -->
    <main class="er-main" v-else-if="page === 'search'">
      <h1 class="er-page-title">Search Records</h1>
      <form class="er-search-form" @submit.prevent="doSearch" id="ctl00_MainContent_searchForm">
        <div class="er-form-grid">
          <div class="er-form-group">
            <label class="er-form-label" for="ctl00_MainContent_txtLastName">Last Name / Firm Name</label>
            <input id="ctl00_MainContent_txtLastName" name="ctl00$MainContent$txtLastName" type="text" class="er-form-input" v-model="searchLastFirm" placeholder="e.g. ARMOK HOLDINGS" />
          </div>
          <div class="er-form-group">
            <label class="er-form-label" for="ctl00_MainContent_txtFirstName">First Name</label>
            <input id="ctl00_MainContent_txtFirstName" name="ctl00$MainContent$txtFirstName" type="text" class="er-form-input" v-model="searchFirst" />
          </div>
          <div class="er-form-group">
            <label class="er-form-label" for="ctl00_MainContent_txtDateFrom">Record Date From</label>
            <input id="ctl00_MainContent_txtDateFrom" name="ctl00$MainContent$txtDateFrom" type="text" class="er-form-input" v-model="searchDateFrom" placeholder="MM/DD/YYYY" />
          </div>
          <div class="er-form-group">
            <label class="er-form-label" for="ctl00_MainContent_txtDateTo">Record Date To</label>
            <input id="ctl00_MainContent_txtDateTo" name="ctl00$MainContent$txtDateTo" type="text" class="er-form-input" v-model="searchDateTo" placeholder="MM/DD/YYYY" />
          </div>
          <div class="er-form-group">
            <label class="er-form-label" for="ctl00_MainContent_ddlIndex">Index Type</label>
            <select id="ctl00_MainContent_ddlIndex" name="ctl00$MainContent$ddlIndex" class="er-form-select" v-model="searchIndex">
              <option value="ALL">All Types</option>
              <option v-for="t in indexTypes" :key="t" :value="t">{{ t }} — {{ indexLabels[t] }}</option>
            </select>
          </div>
        </div>
        <input type="hidden" name="__VIEWSTATE" value="dGhpc0lzTm90UmVhbFZpZXdTdGF0ZQ==" />
        <input type="hidden" name="__EVENTVALIDATION" value="QScrapeL2Test" />
        <div class="er-form-actions">
          <button type="submit" class="er-search-btn" id="ctl00_MainContent_btnSearch" name="ctl00$MainContent$btnSearch">Search</button>
          <button type="button" class="er-clear-btn" @click="clearSearch">Clear</button>
        </div>
      </form>

      <div class="er-results" id="ctl00_MainContent_resultsPanel">
        <div class="er-results-header">
          <span class="er-results-count">{{ searchResults.length }} record{{ searchResults.length !== 1 ? 's' : '' }} found</span>
          <span v-if="totalSearchPages > 1" class="er-results-paging">Page {{ searchPage }} of {{ totalSearchPages }}</span>
        </div>
        <div class="er-table-wrap">
          <table class="er-results-table" id="ctl00_MainContent_gvResults">
            <thead>
              <tr class="er-table-head">
                <th>File #</th><th>Index</th><th>Record Date</th><th>SAT</th><th>Last / Firm</th><th>First</th><th>Amount</th><th>Status</th><th>View</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(d, i) in pagedResults" :key="d.fileNum"
                :class="i % 2 === 0 ? 'er-table-row' : 'er-table-row-alt'"
                :data-file-num="d.fileNum">
                <td class="er-file-num">{{ d.fileNum }}</td>
                <td><span class="er-index-badge">{{ d.index }}</span></td>
                <td class="er-record-date">{{ d.recordDate }}</td>
                <td>{{ d.sat ? 'SAT' : '' }}</td>
                <td>{{ d.lastFirm }}</td>
                <td>{{ d.first }}</td>
                <td class="er-amount">{{ d.amount }}</td>
                <td><span :class="['er-status', 'er-status-' + d.status.toLowerCase()]">{{ d.status }}</span></td>
                <td><button class="er-view-btn" @click="navigate('viewer', d.fileNum)">View</button></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div v-if="totalSearchPages > 1" class="er-pagination">
          <button v-for="p in totalSearchPages" :key="p"
            :class="['er-page-btn', { 'er-page-btn--active': searchPage === p }]"
            @click="searchPage = p">{{ p }}</button>
        </div>
      </div>
    </main>

    <!-- Viewer -->
    <main class="er-main" v-else-if="page === 'viewer'">
      <div v-if="currentRecord">
        <nav class="er-breadcrumb">
          <button @click="navigate('home')">Home</button> /
          <button @click="navigate('search')">Search</button> /
          <span>File {{ currentRecord.fileNum }}</span>
        </nav>
        <div class="er-viewer-header">
          <h1 class="er-viewer-title">Document Viewer</h1>
          <div class="er-viewer-meta">
            <span>File No: <strong>{{ currentRecord.fileNum }}</strong></span>
            <span>Index: <strong>{{ currentRecord.index }}</strong> — {{ indexLabels[currentRecord.index] }}</span>
            <span>Filed: <strong>{{ currentRecord.recordDate }}</strong></span>
            <span>Recorded: <strong class="er-recorded-stamp">RECORDED</strong></span>
          </div>
        </div>
        <div class="er-viewer-detail">
          <table class="er-detail-table">
            <tbody>
              <tr><th>File Number</th><td data-field="file-num">{{ currentRecord.fileNum }}</td></tr>
              <tr><th>Index Type</th><td data-field="index">{{ currentRecord.index }} — {{ indexLabels[currentRecord.index] }}</td></tr>
              <tr><th>Record Date</th><td data-field="record-date">{{ currentRecord.recordDate }}</td></tr>
              <tr><th>Satisfied</th><td data-field="sat">{{ currentRecord.sat ? 'Yes' : 'No' }}</td></tr>
              <tr><th>Last Name / Firm</th><td data-field="last-firm">{{ currentRecord.lastFirm }}</td></tr>
              <tr><th>First Name</th><td data-field="first">{{ currentRecord.first || '—' }}</td></tr>
              <tr><th>Amount</th><td data-field="amount">{{ currentRecord.amount }}</td></tr>
              <tr><th>Status</th><td><span :class="['er-status', 'er-status-' + currentRecord.status.toLowerCase()]">{{ currentRecord.status }}</span></td></tr>
            </tbody>
          </table>
        </div>
        <div class="er-pdf-viewer">
          <div class="er-pdf-header">Document: {{ currentRecord.fileNum }}.pdf</div>
          <iframe :src="'/' + currentRecord.fileNum + '.pdf'" class="er-pdf-frame" />
        </div>
      </div>
      <div v-else class="er-not-found">
        <h1>Record not found</h1>
        <button @click="navigate('search')">← Back to Search</button>
      </div>
    </main>

    <!-- How-to -->
    <main class="er-main" v-else-if="page === 'howto'">
      <h1 class="er-page-title">How-To Guides</h1>
      <div class="er-guides-grid">
        <div v-for="(g, i) in guides" :key="g.type" class="er-guide-card" :data-guide-type="g.type">
          <div class="er-guide-num">Step {{ i + 1 }}</div>
          <div class="er-guide-type">{{ g.type }}</div>
          <h2 class="er-guide-title">{{ g.title }}</h2>
          <ol class="er-guide-steps">
            <li v-for="step in g.steps" :key="step">{{ step }}</li>
          </ol>
          <a :href="'/how-to/' + g.file + '.pdf'" class="er-guide-pdf" target="_blank" rel="noopener">Download PDF Guide ↗</a>
        </div>
      </div>
    </main>

    <!-- Fees -->
    <main class="er-main" v-else-if="page === 'fees'">
      <h1 class="er-page-title">Recording Fee Schedule</h1>
      <p class="er-fees-intro">Current fees effective Year 312. All amounts in Gold Sovereigns (GS).</p>
      <div class="er-table-wrap">
        <table class="er-fees-table">
          <thead>
            <tr><th>Instrument Type</th><th>First Page</th><th>Each Additional Page</th><th>Notes</th></tr>
          </thead>
          <tbody>
            <tr v-for="(f, i) in fees" :key="f.type" :class="i % 2 === 0 ? 'er-table-row' : 'er-table-row-alt'" :data-fee-type="f.type">
              <td><strong>{{ f.type }}</strong> — {{ f.label }}</td>
              <td>{{ f.firstPage }}</td>
              <td>{{ f.addlPage }}</td>
              <td class="er-fee-note">{{ f.notes || '—' }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="er-fees-note">
        <h2>Payment Methods</h2>
        <p>Gold Sovereigns (GS) accepted at counter. Copper Coins (CC) accepted at 1:100 exchange rate.</p>
      </div>
    </main>

    <footer class="er-footer">
      <div class="er-footer-inner">
        <p>Eldoria Registry of Deeds · Granite Flats County · Year 312</p>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { fakeGet } from '../../../../data/api';
import { deeds, searchDeeds } from '../../../../data/taxes/deeds';

type Page = 'home' | 'search' | 'viewer' | 'howto' | 'fees';

// ── URL routing helpers ────────────────────────────────────────────────────
function getBase() {
	return `/${window.location.pathname.split('/').filter(Boolean).slice(0, 3).join('/')}/`;
}
function pathToState(): { page: Page; fileNum?: string } {
	const seg = window.location.pathname.split('/').filter(Boolean).at(-1) ?? '';
	const p = new URLSearchParams(window.location.search);
	if (seg === 'search') {
		return { page: 'search' };
	}
	if (seg === 'viewer') {
		return { page: 'viewer', fileNum: p.get('file') ?? undefined };
	}
	if (seg === 'how-to') {
		return { page: 'howto' };
	}
	if (seg === 'recording-fees') {
		return { page: 'fees' };
	}
	return { page: 'home' };
}
function pageToPath(p: Page, extra?: string) {
	const base = getBase();
	if (p === 'search') {
		return `${base}search`;
	}
	if (p === 'viewer') {
		return `${base}viewer${extra ? `?file=${encodeURIComponent(extra)}` : ''}`;
	}
	if (p === 'howto') {
		return `${base}how-to`;
	}
	if (p === 'fees') {
		return `${base}recording-fees`;
	}
	return base;
}

const ready = ref(false);
const page = ref<Page>('home');
const currentFileNum = ref('');
const searchLastFirm = ref('');
const searchFirst = ref('');
const searchDateFrom = ref('');
const searchDateTo = ref('');
const searchIndex = ref('ALL');
const searchPage = ref(1);
const PER_PAGE = 10;

const _navPages = [
	{ id: 'home' as Page, label: 'Home' },
	{ id: 'search' as Page, label: 'Search Records' },
	{ id: 'howto' as Page, label: 'How-To Guides' },
	{ id: 'fees' as Page, label: 'Recording Fees' },
];

const searchResults = ref(deeds);
const _totalSearchPages = computed(() =>
	Math.ceil(searchResults.value.length / PER_PAGE),
);
const _pagedResults = computed(() =>
	searchResults.value.slice(
		(searchPage.value - 1) * PER_PAGE,
		searchPage.value * PER_PAGE,
	),
);
const _currentRecord = computed(() =>
	deeds.find((d) => d.fileNum === currentFileNum.value),
);

function _navigate(p: Page, extra?: string) {
	page.value = p;
	if (p === 'viewer' && extra) {
		currentFileNum.value = extra;
	}
	history.pushState(null, '', pageToPath(p, extra));
	window.scrollTo(0, 0);
}

function onPop() {
	const s = pathToState();
	page.value = s.page;
	if (s.fileNum) {
		currentFileNum.value = s.fileNum;
	}
	window.scrollTo(0, 0);
}
onMounted(() => {
	const s = pathToState();
	page.value = s.page;
	if (s.fileNum) {
		currentFileNum.value = s.fileNum;
	}
	window.addEventListener('popstate', onPop);
	fakeGet(null).then(() => {
		ready.value = true;
	});
});
onUnmounted(() => window.removeEventListener('popstate', onPop));

function _doSearch() {
	searchResults.value = searchDeeds({
		lastFirm: searchLastFirm.value,
		first: searchFirst.value,
		index: searchIndex.value === 'ALL' ? undefined : searchIndex.value,
	});
	searchPage.value = 1;
}

function _clearSearch() {
	searchLastFirm.value = '';
	searchFirst.value = '';
	searchDateFrom.value = '';
	searchDateTo.value = '';
	searchIndex.value = 'ALL';
	searchResults.value = deeds;
	searchPage.value = 1;
}

const _guides = [
	{
		type: 'DEED',
		file: 'how-to-deed',
		title: 'How to Read a Deed',
		steps: [
			'Locate the grantor and grantee names.',
			'Identify the property description.',
			'Check for any reservations or exceptions.',
			'Verify the notarization and recording stamp.',
		],
	},
	{
		type: 'MTG',
		file: 'how-to-mtg',
		title: 'How to Read a Mortgage',
		steps: [
			'Identify the mortgagor and mortgagee.',
			'Locate the principal amount and interest rate.',
			'Check the maturity date.',
			'Review any satisfaction filings.',
		],
	},
	{
		type: 'LIEN',
		file: 'how-to-lien',
		title: 'How to Read a Lien',
		steps: [
			'Identify the lienor and lienee.',
			'Determine the lien amount.',
			'Check whether a satisfaction has been recorded.',
			'Review related deed filings.',
		],
	},
	{
		type: 'ESMT',
		file: 'how-to-esmt',
		title: 'How to Read an Easement',
		steps: [
			'Identify the dominant and servient estates.',
			'Locate the easement purpose.',
			'Check for conditions or expiration terms.',
			'Review plat map references.',
		],
	},
	{
		type: 'AFF',
		file: 'how-to-aff',
		title: 'How to Read an Affidavit',
		steps: [
			'Identify the affiant and notary.',
			'Locate the statement of facts.',
			'Check the notarization date and seal.',
			'Review any exhibits cited.',
		],
	},
	{
		type: 'ASGN',
		file: 'how-to-asgn',
		title: 'How to Read an Assignment',
		steps: [
			'Identify the assignor and assignee.',
			'Locate the original instrument being assigned.',
			'Check the effective date.',
			'Verify recording stamps.',
		],
	},
	{
		type: 'NTC',
		file: 'how-to-ntc',
		title: 'How to Read a Notice',
		steps: [
			'Identify the parties giving and receiving notice.',
			'Locate the subject matter.',
			'Check the notice date.',
			'Review related filings.',
		],
	},
	{
		type: 'REL',
		file: 'how-to-rel',
		title: 'How to Read a Release',
		steps: [
			'Identify the releasing and released parties.',
			'Locate the original instrument.',
			'Check the effective release date.',
			'Confirm satisfaction recording.',
		],
	},
];

const _fees = [
	{
		type: 'DEED',
		label: 'Deed',
		firstPage: '15.00 GS',
		addlPage: '3.00 GS',
		notes: 'Includes transfer tax',
	},
	{
		type: 'MTG',
		label: 'Mortgage',
		firstPage: '20.00 GS',
		addlPage: '3.00 GS',
		notes: 'Plus 0.5% of principal',
	},
	{
		type: 'LIEN',
		label: 'Lien',
		firstPage: '9.00 GS',
		addlPage: '3.00 GS',
		notes: '',
	},
	{
		type: 'ESMT',
		label: 'Easement',
		firstPage: '12.00 GS',
		addlPage: '3.00 GS',
		notes: '',
	},
	{
		type: 'AFF',
		label: 'Affidavit',
		firstPage: '10.00 GS',
		addlPage: '2.00 GS',
		notes: '',
	},
	{
		type: 'ASGN',
		label: 'Assignment',
		firstPage: '12.00 GS',
		addlPage: '2.00 GS',
		notes: '',
	},
	{
		type: 'NTC',
		label: 'Notice',
		firstPage: '8.00 GS',
		addlPage: '2.00 GS',
		notes: '',
	},
	{
		type: 'REL',
		label: 'Release',
		firstPage: '0.00 GS',
		addlPage: '0.00 GS',
		notes: 'No fee for release recording',
	},
];
</script>

<style scoped>
.er-shell { min-height: 100vh; background: #f8f9fa; color: #212529; font-family: 'IBM Plex Sans', system-ui, sans-serif; }
.er-header { background: #fff; border-bottom: 3px solid #1d4ed8; }
.er-header-top { background: #1d4ed8; }
.er-header-inner { max-width: 1100px; margin: 0 auto; padding: 16px 24px; display: flex; justify-content: space-between; align-items: center; }
.er-brand { display: flex; align-items: center; gap: 14px; }
.er-crest { font-size: 32px; }
.er-title { font-size: 20px; font-weight: 700; color: #fff; }
.er-sub { font-size: 12px; color: rgba(255,255,255,0.75); margin-top: 2px; }
.er-meta { text-align: right; font-size: 12px; color: rgba(255,255,255,0.75); }
.er-version { font-family: monospace; font-size: 11px; color: rgba(255,255,255,0.5); margin-top: 2px; }
.er-nav { background: #fff; border-bottom: 1px solid #ced4da; }
.er-nav-inner { max-width: 1100px; margin: 0 auto; padding: 0 24px; display: flex; }
.er-nav-item { background: none; border: none; cursor: pointer; padding: 12px 16px; font-size: 14px; color: #212529; border-bottom: 3px solid transparent; margin-bottom: -1px; font-weight: 500; }
.er-nav-item:hover { color: #1d4ed8; }
.er-nav-item--active { color: #1d4ed8; border-bottom-color: #1d4ed8; }
.er-main { max-width: 1100px; margin: 0 auto; padding: 32px 24px; }
.er-status { display: inline-block; font-size: 11px; font-weight: 700; padding: 2px 8px; border-radius: 2px; text-transform: uppercase; letter-spacing: 0.05em; }
.er-status-recorded { background: #dcfce7; color: #166534; }
.er-status-satisfied { background: #dbeafe; color: #1e3a5f; }
.er-status-delinquent { background: #fee2e2; color: #7c2d12; }
.er-hero { background: #1d4ed8; color: #fff; padding: 48px 40px; border-radius: 4px; margin-bottom: 32px; }
.er-hero-title { font-size: 32px; font-weight: 700; margin-bottom: 12px; }
.er-hero-sub { font-size: 16px; opacity: 0.9; margin-bottom: 24px; }
.er-hero-btn { background: #fff; color: #1d4ed8; border: none; padding: 12px 24px; font-size: 15px; font-weight: 600; cursor: pointer; border-radius: 4px; }
.er-hero-btn:hover { background: #f0f9ff; }
.er-home-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 32px; }
@media (max-width: 700px) { .er-home-grid { grid-template-columns: 1fr; } }
.er-home-card { background: #fff; border: 1px solid #ced4da; padding: 24px; border-radius: 4px; }
.er-home-icon { font-size: 28px; margin-bottom: 12px; }
.er-home-card-title { font-size: 18px; font-weight: 700; margin-bottom: 8px; }
.er-home-card-desc { font-size: 14px; color: #6c757d; line-height: 1.6; margin-bottom: 16px; }
.er-home-card-btn { background: none; border: 1px solid #1d4ed8; color: #1d4ed8; padding: 8px 16px; font-size: 14px; cursor: pointer; border-radius: 4px; font-weight: 500; }
.er-home-card-btn:hover { background: #1d4ed8; color: #fff; }
.er-office-hours { background: #fff; border: 1px solid #ced4da; padding: 24px; border-radius: 4px; }
.er-oh-title { font-size: 18px; font-weight: 700; margin-bottom: 16px; }
.er-oh-table { border-collapse: collapse; }
.er-oh-table td { padding: 6px 24px 6px 0; font-size: 14px; }
.er-oh-table td:first-child { font-weight: 600; }
.er-page-title { font-size: 28px; font-weight: 700; margin-bottom: 24px; }
.er-search-form { background: #fff; border: 1px solid #ced4da; padding: 24px; border-radius: 4px; margin-bottom: 24px; }
.er-form-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-bottom: 16px; }
@media (max-width: 600px) { .er-form-grid { grid-template-columns: 1fr; } }
.er-form-group { display: flex; flex-direction: column; gap: 6px; }
.er-form-label { font-size: 13px; font-weight: 600; }
.er-form-input { padding: 8px 12px; border: 1px solid #ced4da; border-radius: 4px; font-size: 14px; outline: none; }
.er-form-input:focus { border-color: #3b82f6; box-shadow: 0 0 0 3px rgba(59,130,246,0.15); }
.er-form-select { padding: 8px 12px; border: 1px solid #ced4da; border-radius: 4px; font-size: 14px; background: #fff; outline: none; }
.er-form-actions { display: flex; gap: 12px; }
.er-search-btn { background: #1d4ed8; color: #fff; border: none; padding: 10px 24px; font-size: 14px; font-weight: 600; cursor: pointer; border-radius: 4px; }
.er-search-btn:hover { background: #1e40af; }
.er-clear-btn { background: none; border: 1px solid #ced4da; padding: 10px 24px; font-size: 14px; cursor: pointer; border-radius: 4px; }
.er-clear-btn:hover { border-color: #1d4ed8; color: #1d4ed8; }
.er-results { }
.er-results-header { display: flex; justify-content: space-between; font-size: 13px; color: #6c757d; margin-bottom: 12px; }
.er-table-wrap { overflow-x: auto; border: 1px solid #ced4da; border-radius: 4px; }
.er-results-table { width: 100%; border-collapse: collapse; font-size: 13px; }
.er-fees-table { width: 100%; border-collapse: collapse; font-size: 14px; }
.er-results-table th, .er-fees-table th { background: #1d4ed8; color: #fff; padding: 10px 12px; text-align: left; font-weight: 600; white-space: nowrap; }
.er-table-head th { background: #1d4ed8; color: #fff; padding: 10px 12px; text-align: left; font-weight: 600; white-space: nowrap; }
.er-table-row { background: #fff; }
.er-table-row-alt { background: #f8f9fa; }
.er-table-row td, .er-table-row-alt td, .er-fees-table td { padding: 10px 12px; border-bottom: 1px solid #ced4da; vertical-align: middle; }
.er-file-num { font-family: monospace; font-weight: 600; }
.er-index-badge { background: #f8f9fa; border: 1px solid #ced4da; padding: 2px 6px; border-radius: 2px; font-size: 11px; font-weight: 700; letter-spacing: 0.04em; }
.er-record-date { white-space: nowrap; }
.er-amount { font-family: monospace; white-space: nowrap; }
.er-view-btn { background: #1d4ed8; color: #fff; border: none; padding: 4px 12px; font-size: 12px; cursor: pointer; border-radius: 2px; font-weight: 500; }
.er-view-btn:hover { background: #1e40af; }
.er-pagination { display: flex; justify-content: center; gap: 8px; margin-top: 16px; }
.er-page-btn { background: none; border: 1px solid #ced4da; padding: 6px 12px; cursor: pointer; border-radius: 2px; font-size: 13px; }
.er-page-btn:hover { border-color: #1d4ed8; color: #1d4ed8; }
.er-page-btn--active { background: #1d4ed8; border-color: #1d4ed8; color: #fff; }
.er-breadcrumb { font-size: 13px; color: #6c757d; margin-bottom: 24px; }
.er-breadcrumb button { background: none; border: none; cursor: pointer; color: #1d4ed8; font-size: 13px; }
.er-breadcrumb button:hover { text-decoration: underline; }
.er-viewer-header { background: #fff; border: 1px solid #ced4da; padding: 20px 24px; border-radius: 4px; margin-bottom: 20px; }
.er-viewer-title { font-size: 22px; font-weight: 700; margin-bottom: 12px; }
.er-viewer-meta { display: flex; flex-wrap: wrap; gap: 16px; font-size: 13px; color: #6c757d; }
.er-viewer-meta strong { color: #212529; }
.er-recorded-stamp { color: #166534; background: #dcfce7; padding: 2px 8px; border-radius: 2px; }
.er-viewer-detail { background: #fff; border: 1px solid #ced4da; border-radius: 4px; overflow: hidden; margin-bottom: 20px; }
.er-detail-table { width: 100%; border-collapse: collapse; font-size: 14px; }
.er-detail-table th { background: #f8f9fa; padding: 10px 16px; text-align: left; font-weight: 600; border-bottom: 1px solid #ced4da; width: 200px; }
.er-detail-table td { padding: 10px 16px; border-bottom: 1px solid #ced4da; }
.er-detail-table tr:last-child th, .er-detail-table tr:last-child td { border-bottom: none; }
.er-pdf-viewer { background: #fff; border: 1px solid #ced4da; border-radius: 4px; overflow: hidden; }
.er-pdf-header { background: #f8f9fa; padding: 10px 16px; font-size: 13px; font-weight: 600; border-bottom: 1px solid #ced4da; }
.er-pdf-frame { width: 100%; height: 600px; border: none; display: block; }
.er-not-found { text-align: center; padding: 60px 24px; }
.er-not-found button { margin-top: 16px; background: #1d4ed8; color: #fff; border: none; padding: 10px 20px; cursor: pointer; border-radius: 4px; font-size: 14px; }
.er-guides-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; }
@media (max-width: 700px) { .er-guides-grid { grid-template-columns: 1fr; } }
.er-guide-card { background: #fff; border: 1px solid #ced4da; padding: 24px; border-radius: 4px; }
.er-guide-num { font-size: 11px; color: #6c757d; text-transform: uppercase; letter-spacing: 0.06em; margin-bottom: 4px; }
.er-guide-type { display: inline-block; background: #1d4ed8; color: #fff; padding: 2px 8px; font-size: 12px; font-weight: 700; border-radius: 2px; margin-bottom: 10px; }
.er-guide-title { font-size: 18px; font-weight: 700; margin-bottom: 14px; }
.er-guide-steps { padding-left: 20px; margin-bottom: 16px; }
.er-guide-steps li { font-size: 14px; line-height: 1.6; margin-bottom: 6px; }
.er-guide-pdf { font-size: 13px; color: #1d4ed8; font-weight: 500; }
.er-guide-pdf:hover { text-decoration: underline; }
.er-fees-intro { color: #6c757d; margin-bottom: 24px; }
.er-fee-note { color: #6c757d; font-style: italic; }
.er-fees-note { background: #fff; border: 1px solid #ced4da; padding: 24px; border-radius: 4px; margin-top: 24px; }
.er-fees-note h2 { font-size: 16px; font-weight: 700; margin-bottom: 8px; }
.er-fees-note p { font-size: 14px; line-height: 1.6; margin-bottom: 16px; }
.er-footer { border-top: 1px solid #ced4da; margin-top: 48px; background: #fff; }
.er-footer-inner { max-width: 1100px; margin: 0 auto; padding: 16px 24px; font-size: 13px; color: #6c757d; }
</style>

// src/components/l2/svelte/taxes/TaxesApp.svelte
<script lang="ts">
// @qscrape L2 / svelte / taxes — Eldoria Registry of Deeds
import { onDestroy, onMount } from 'svelte';
import '../../../../styles/l2/taxes.css';
import { fakeGet } from '../../../../data/api';
import {
	type DeedRecord,
	getDeedByFileNum,
	searchDeeds,
} from '../../../../data/taxes/deeds';

type Page = 'home' | 'search' | 'viewer' | 'howto' | 'fees';

function getBase(): string {
	return `/${window.location.pathname.split('/').filter(Boolean).slice(0, 3).join('/')}/`;
}
function urlToPage(): { page: Page; fileNum?: string } {
	const seg = window.location.pathname.split('/').filter(Boolean).at(-1) ?? '';
	const p = new URLSearchParams(window.location.search);
	if (seg === 'search') {
		return { page: 'search' };
	}
	if (seg === 'viewer') {
		return { page: 'viewer', fileNum: p.get('file') ?? undefined };
	}
	if (seg === 'how-to') {
		return { page: 'howto' };
	}
	if (seg === 'recording-fees') {
		return { page: 'fees' };
	}
	return { page: 'home' };
}
function pageToUrl(p: Page, extra?: string): string {
	const base = getBase();
	if (p === 'search') {
		return `${base}search`;
	}
	if (p === 'viewer') {
		return `${base}viewer${extra ? `?file=${encodeURIComponent(extra)}` : ''}`;
	}
	if (p === 'howto') {
		return `${base}how-to`;
	}
	if (p === 'fees') {
		return `${base}recording-fees`;
	}
	return base;
}

let _ready = false;
let _current: Page = 'home';

// Search state
const fLastFirm = '';
const fFirst = '';
const fIndex = 'ALL';
let searchResults: DeedRecord[] = [];
let _hasSearched = false;
let currentPage = 1;
const PER_PAGE = 10;

// Viewer state
let _viewerDoc: DeedRecord | null = null;

function nav(p: Page, extra?: string) {
	_current = p;
	history.pushState(null, '', pageToUrl(p, extra));
	window.scrollTo(0, 0);
}

function onPop() {
	const s = urlToPage();
	_current = s.page;
	if (s.fileNum) {
		_viewerDoc = getDeedByFileNum(s.fileNum) ?? null;
	}
	window.scrollTo(0, 0);
}
onMount(() => {
	const s = urlToPage();
	_current = s.page;
	if (s.fileNum) {
		_viewerDoc = getDeedByFileNum(s.fileNum) ?? null;
	}
	window.addEventListener('popstate', onPop);
	fakeGet(null).then(() => {
		_ready = true;
	});
});
onDestroy(() => window.removeEventListener('popstate', onPop));

function _doSearch() {
	_hasSearched = true;
	currentPage = 1;
	searchResults = searchDeeds({
		lastFirm: fLastFirm,
		first: fFirst,
		index: fIndex,
	});
}

$: pagedResults = searchResults.slice(
	(currentPage - 1) * PER_PAGE,
	currentPage * PER_PAGE,
);
$: totalPages = Math.ceil(searchResults.length / PER_PAGE);

function _openViewer(d: DeedRecord) {
	_viewerDoc = d;
	nav('viewer', d.fileNum);
}

function _statusClass(s: string) {
	if (s === 'RECORDED') {
		return 'er-status-recorded';
	}
	if (s === 'SATISFIED') {
		return 'er-status-satisfied';
	}
	return 'er-status-delinquent';
}

const _feeTable = [
	{ type: 'Deed', first: '10.00 GS', add: '2.00 GS/page' },
	{ type: 'Mortgage', first: '15.00 GS', add: '2.50 GS/page' },
	{ type: 'Lien', first: '12.00 GS', add: '2.00 GS/page' },
	{ type: 'Release', first: '8.00 GS', add: '1.50 GS/page' },
	{ type: 'Assignment', first: '10.00 GS', add: '2.00 GS/page' },
	{ type: 'Easement', first: '10.00 GS', add: '2.00 GS/page' },
	{ type: 'Affidavit', first: '8.00 GS', add: '1.50 GS/page' },
	{ type: 'Notice', first: '6.00 GS', add: '1.00 GS/page' },
];

const _howToGuides = [
	{
		id: 'deed',
		title: 'How to Search Deed Records',
		desc: 'Step-by-step guide to searching the grantor–grantee index.',
	},
	{
		id: 'mtg',
		title: 'How to Search Mortgage Records',
		desc: 'Finding mortgage originations and satisfactions.',
	},
	{
		id: 'lien',
		title: 'How to Search Lien Records',
		desc: 'Identifying active liens and delinquent obligations.',
	},
	{
		id: 'cert',
		title: 'Obtaining Certified Copies',
		desc: 'Requesting certified copies of recorded instruments.',
	},
	{
		id: 'efiling',
		title: 'e-Filing Instructions',
		desc: 'Submitting documents electronically via the Rune-Wire system.',
	},
	{
		id: 'fees',
		title: 'Recording Fee Schedule',
		desc: 'Current fees for all document types.',
	},
	{
		id: 'tract',
		title: 'Tract Index Guide',
		desc: 'Using parcel-based search to find all encumbrances.',
	},
	{
		id: 'hist',
		title: 'Historical Research Guide',
		desc: 'Searching records prior to Year 200.',
	},
];
</script>

{#if !ready}
  <div style="display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:'IBM Plex Sans',system-ui;color:#6c757d;background:#f8f9fa">Loading…</div>
{:else}
<div class="er-shell">
  <!-- Header -->
  <header class="er-header">
    <div class="er-header-inner">
      <div class="er-header-title">
        <span class="er-crest" aria-hidden="true">⚖</span>
        <div>
          <h1 class="er-site-title">Eldoria Registry of Deeds</h1>
          <p class="er-site-subtitle">Grand Duchy of Mountainhome · Bureau of Land Records</p>
        </div>
      </div>
    </div>
    <nav class="er-nav">
      <button class="er-nav-btn{current === 'home' ? ' active' : ''}" on:click={() => nav('home')}>Home</button>
      <button class="er-nav-btn{current === 'search' ? ' active' : ''}" on:click={() => nav('search')}>Search Records</button>
      <button class="er-nav-btn{current === 'viewer' ? ' active' : ''}" on:click={() => nav('viewer')}>Document Viewer</button>
      <button class="er-nav-btn{current === 'howto' ? ' active' : ''}" on:click={() => nav('howto')}>How-To Guides</button>
      <button class="er-nav-btn{current === 'fees' ? ' active' : ''}" on:click={() => nav('fees')}>Recording Fees</button>
    </nav>
  </header>

  <main class="er-main">
    <!-- HOME PAGE -->
    {#if current === 'home'}
      <div class="er-notice" role="note">
        <strong>Notice:</strong> The Registry is open Monday–Friday, 8:00 AM – 4:30 PM. Documents recorded by 3:00 PM receive same-day indexing.
      </div>
      <div class="er-home-grid">
        <section class="er-panel">
          <h2>Search Records</h2>
          <p>Search deed, mortgage, lien, and other recorded documents by name or document type.</p>
          <button class="er-btn-primary" on:click={() => nav('search')}>Search the Index</button>
        </section>
        <section class="er-panel">
          <h2>Document Viewer</h2>
          <p>View and download images of recorded instruments. PDF format available for all post-Year 280 filings.</p>
          <button class="er-btn-primary" on:click={() => nav('viewer')}>Open Viewer</button>
        </section>
        <section class="er-panel">
          <h2>How-To Guides</h2>
          <p>Step-by-step instructions for searching records, obtaining certified copies, and e-filing documents.</p>
          <button class="er-btn-secondary" on:click={() => nav('howto')}>View Guides</button>
        </section>
        <section class="er-panel">
          <h2>Recording Fees</h2>
          <p>Current fee schedule for recording deeds, mortgages, liens, and all other instruments.</p>
          <button class="er-btn-secondary" on:click={() => nav('fees')}>Fee Schedule</button>
        </section>
      </div>
      <section class="er-recent-section">
        <h2 class="er-section-title">Recently Recorded Instruments</h2>
        <table class="er-table">
          <thead>
            <tr>
              <th>File No.</th>
              <th>Type</th>
              <th>Date Recorded</th>
              <th>Last Name / Firm</th>
              <th>First Name</th>
              <th>Amount</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {#each [...deeds].reverse().slice(0, 5) as d}
              <tr data-file={d.fileNum}>
                <td><button class="er-link-btn" on:click={() => openViewer(d)}>{d.fileNum}</button></td>
                <td>{indexLabels[d.index]}</td>
                <td>{d.recordDate}</td>
                <td>{d.lastFirm}</td>
                <td>{d.first}</td>
                <td>{d.amount}</td>
                <td><span class={statusClass(d.status)}>{d.status}</span></td>
              </tr>
            {/each}
          </tbody>
        </table>
      </section>

    <!-- SEARCH PAGE -->
    {:else if current === 'search'}
      <h2 class="er-page-title">Search Records</h2>
      <form class="er-search-form" on:submit|preventDefault={doSearch}>
        <input type="hidden" name="__VIEWSTATE" value="dGhpcyBpcyBhIGZha2Ugdmlld3N0YXRl" />
        <input type="hidden" name="__EVENTVALIDATION" value="ZXZlbnR2YWxpZGF0aW9u" />
        <div class="er-form-grid">
          <div class="er-form-group">
            <label for="ctl00_MainContent_txtLastFirm">Last Name / Firm Name</label>
            <input
              id="ctl00_MainContent_txtLastFirm"
              name="ctl00$MainContent$txtLastFirm"
              type="text"
              bind:value={fLastFirm}
              placeholder="e.g. ARMOK or MCMINER"
            />
          </div>
          <div class="er-form-group">
            <label for="ctl00_MainContent_txtFirst">First Name</label>
            <input
              id="ctl00_MainContent_txtFirst"
              name="ctl00$MainContent$txtFirst"
              type="text"
              bind:value={fFirst}
              placeholder="e.g. URIST"
            />
          </div>
          <div class="er-form-group">
            <label for="ctl00_MainContent_ddlIndex">Document Type</label>
            <select
              id="ctl00_MainContent_ddlIndex"
              name="ctl00$MainContent$ddlIndex"
              bind:value={fIndex}
            >
              <option value="ALL">All Types</option>
              {#each indexTypes as t}
                <option value={t}>{indexLabels[t]} ({t})</option>
              {/each}
            </select>
          </div>
        </div>
        <div class="er-form-actions">
          <button
            class="er-btn-primary"
            type="submit"
            id="ctl00_MainContent_btnSearch"
            name="ctl00$MainContent$btnSearch"
          >Search</button>
          <button
            class="er-btn-secondary"
            type="button"
            on:click={() => { fLastFirm = ''; fFirst = ''; fIndex = 'ALL'; hasSearched = false; searchResults = []; }}
          >Clear</button>
        </div>
      </form>

      {#if hasSearched}
        <div class="er-results-header">
          <p class="er-result-count">{searchResults.length} result{searchResults.length !== 1 ? 's' : ''} found</p>
        </div>
        {#if searchResults.length > 0}
          <table class="er-table">
            <thead>
              <tr>
                <th>File No.</th>
                <th>Type</th>
                <th>Date Recorded</th>
                <th>Last Name / Firm</th>
                <th>First Name</th>
                <th>SAT</th>
                <th>Amount</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {#each pagedResults as d}
                <tr data-file={d.fileNum}>
                  <td><button class="er-link-btn" on:click={() => openViewer(d)}>{d.fileNum}</button></td>
                  <td>{indexLabels[d.index]}</td>
                  <td>{d.recordDate}</td>
                  <td>{d.lastFirm}</td>
                  <td>{d.first}</td>
                  <td>{d.sat ? 'Y' : 'N'}</td>
                  <td>{d.amount}</td>
                  <td><span class={statusClass(d.status)}>{d.status}</span></td>
                </tr>
              {/each}
            </tbody>
          </table>
          {#if totalPages > 1}
            <div class="er-pagination">
              {#each Array(totalPages) as _, i}
                <button
                  class="er-page-btn{currentPage === i + 1 ? ' active' : ''}"
                  on:click={() => (currentPage = i + 1)}
                >{i + 1}</button>
              {/each}
            </div>
          {/if}
        {:else}
          <p class="er-no-results">No records matched your search criteria.</p>
        {/if}
      {/if}

    <!-- DOCUMENT VIEWER -->
    {:else if current === 'viewer'}
      <h2 class="er-page-title">Document Viewer</h2>
      {#if viewerDoc}
        {@const d = viewerDoc}
        <div class="er-viewer-meta">
          <dl class="er-meta-list">
            <dt>File Number</dt><dd>{d.fileNum}</dd>
            <dt>Document Type</dt><dd>{indexLabels[d.index]} ({d.index})</dd>
            <dt>Date Recorded</dt><dd>{d.recordDate}</dd>
            <dt>Last Name / Firm</dt><dd>{d.lastFirm}</dd>
            <dt>First Name</dt><dd>{d.first || '—'}</dd>
            <dt>Amount</dt><dd>{d.amount}</dd>
            <dt>Satisfied</dt><dd>{d.sat ? 'Yes' : 'No'}</dd>
            <dt>Status</dt><dd><span class={statusClass(d.status)}>{d.status}</span></dd>
          </dl>
        </div>
        <div class="er-pdf-viewer">
          <iframe
            src="/{d.fileNum}.pdf"
            title="Document {d.fileNum}"
            width="100%"
            height="600"
          ></iframe>
        </div>
        <div class="er-viewer-actions">
          <button class="er-btn-secondary" on:click={() => nav('search')}>← Back to Search</button>
          <a class="er-btn-primary" href="/{d.fileNum}.pdf" download>Download PDF</a>
        </div>
      {:else}
        <p class="er-viewer-empty">No document selected. Use <button class="er-link-btn" on:click={() => nav('search')}>Search Records</button> to find a document.</p>
      {/if}

    <!-- HOW-TO GUIDES -->
    {:else if current === 'howto'}
      <h2 class="er-page-title">How-To Guides</h2>
      <p class="er-intro">These guides provide step-by-step instructions for common Registry tasks.</p>
      <div class="er-guide-grid">
        {#each howToGuides as g}
          <div class="er-guide-card" data-guide={g.id}>
            <h3>{g.title}</h3>
            <p>{g.desc}</p>
            <a class="er-guide-link" href="/how-to/{g.id}.pdf" download>Download PDF Guide</a>
          </div>
        {/each}
      </div>

    <!-- RECORDING FEES -->
    {:else if current === 'fees'}
      <h2 class="er-page-title">Recording Fee Schedule</h2>
      <p class="er-intro">Effective Year 312. All amounts in Gold Sovereigns (GS). Payment accepted in GS, Silver Coins (SC), and certified Rune-Wire transfer.</p>
      <table class="er-table er-fee-table">
        <thead>
          <tr>
            <th>Document Type</th>
            <th>First Page</th>
            <th>Each Additional Page</th>
          </tr>
        </thead>
        <tbody>
          {#each feeTable as row}
            <tr>
              <td>{row.type}</td>
              <td>{row.first}</td>
              <td>{row.add}</td>
            </tr>
          {/each}
        </tbody>
      </table>
      <div class="er-fee-notes">
        <h3>Additional Fees</h3>
        <ul>
          <li>Certified copy: 5.00 GS per document</li>
          <li>e-Filing surcharge: 2.00 GS per transaction</li>
          <li>Expedited same-day recording (after 3:00 PM): 10.00 GS surcharge</li>
          <li>Returned payment fee: 25.00 GS</li>
        </ul>
      </div>
    {/if}
  </main>

  <footer class="er-footer">
    <p>Eldoria Registry of Deeds · Grand Duchy of Mountainhome · Z-Level 3 Administrative Complex · Open Mon–Fri 8:00 AM–4:30 PM</p>
  </footer>
</div>
{/if}

<style>
  .er-shell { min-height: 100vh; display: flex; flex-direction: column; }

  /* Header */
  .er-header { background: var(--er-primary); color: #fff; }
  .er-header-inner { max-width: 1100px; margin: 0 auto; padding: 16px 24px; }
  .er-header-title { display: flex; align-items: center; gap: 16px; }
  .er-crest { font-size: 2rem; }
  .er-site-title { font-size: 1.4rem; font-weight: 700; }
  .er-site-subtitle { font-size: 12px; opacity: 0.8; }
  .er-nav { background: rgba(0,0,0,0.2); }
  .er-nav { max-width: 1100px; margin: 0 auto; padding: 0 24px; display: flex; gap: 0; flex-wrap: wrap; }
  .er-nav-btn { background: none; border: none; color: rgba(255,255,255,0.8); font-family: var(--er-font); font-size: 13px; padding: 10px 16px; cursor: pointer; border-bottom: 3px solid transparent; }
  .er-nav-btn:hover, .er-nav-btn.active { color: #fff; border-bottom-color: #fff; background: rgba(255,255,255,0.1); }

  /* Main */
  .er-main { flex: 1; max-width: 1100px; margin: 0 auto; width: 100%; padding: 28px 24px; }
  .er-notice { background: #fff3cd; border: 1px solid #ffc107; border-radius: var(--er-radius); padding: 12px 16px; font-size: 13px; margin-bottom: 24px; }
  .er-page-title { font-size: 1.5rem; font-weight: 700; margin-bottom: 20px; border-bottom: 2px solid var(--er-border); padding-bottom: 8px; }

  /* Home grid */
  .er-home-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 16px; margin-bottom: 36px; }
  .er-panel { background: var(--er-surface); border: 1px solid var(--er-border); border-radius: var(--er-radius); padding: 20px; }
  .er-panel h2 { font-size: 1rem; font-weight: 700; margin-bottom: 8px; color: var(--er-primary); }
  .er-panel p { font-size: 13px; color: var(--er-muted); margin-bottom: 16px; }

  /* Section */
  .er-section-title { font-size: 1.1rem; font-weight: 700; margin-bottom: 12px; }
  .er-recent-section { margin-top: 8px; }

  /* Table */
  .er-table { width: 100%; border-collapse: collapse; font-size: 13px; background: var(--er-surface); border: 1px solid var(--er-border); border-radius: var(--er-radius); overflow: hidden; }
  .er-table th { background: var(--er-primary); color: #fff; text-align: left; padding: 10px 12px; font-size: 12px; letter-spacing: 0.04em; }
  .er-table td { padding: 10px 12px; border-bottom: 1px solid var(--er-border); }
  .er-table tr:last-child td { border-bottom: none; }
  .er-table tr:hover td { background: #f1f5ff; }
  .er-link-btn { background: none; border: none; color: var(--er-primary); font-family: var(--er-font); font-size: inherit; cursor: pointer; padding: 0; text-decoration: underline; }

  /* Status badges */
  :global(.er-status-recorded) { background: var(--er-recorded-bg); color: var(--er-recorded); font-size: 11px; font-weight: 700; padding: 2px 7px; border-radius: 3px; letter-spacing: 0.04em; }
  :global(.er-status-satisfied) { background: var(--er-satisfied-bg); color: var(--er-satisfied); font-size: 11px; font-weight: 700; padding: 2px 7px; border-radius: 3px; letter-spacing: 0.04em; }
  :global(.er-status-delinquent) { background: var(--er-delinquent-bg); color: var(--er-delinquent); font-size: 11px; font-weight: 700; padding: 2px 7px; border-radius: 3px; letter-spacing: 0.04em; }

  /* Search form */
  .er-search-form { background: var(--er-surface); border: 1px solid var(--er-border); border-radius: var(--er-radius); padding: 24px; margin-bottom: 24px; }
  .er-form-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 16px; margin-bottom: 16px; }
  .er-form-group { display: flex; flex-direction: column; gap: 4px; }
  .er-form-group label { font-size: 13px; font-weight: 600; color: var(--er-text); }
  .er-form-group input, .er-form-group select { padding: 8px 10px; border: 1px solid var(--er-border); border-radius: var(--er-radius); font-family: var(--er-font); font-size: 14px; background: var(--er-surface); color: var(--er-text); }
  .er-form-group input:focus, .er-form-group select:focus { outline: 2px solid var(--er-focus); border-color: var(--er-focus); }
  .er-form-actions { display: flex; gap: 10px; }
  .er-results-header { margin-bottom: 12px; }
  .er-result-count { font-size: 13px; color: var(--er-muted); }
  .er-no-results { font-size: 14px; color: var(--er-muted); padding: 24px; text-align: center; background: var(--er-surface); border: 1px solid var(--er-border); border-radius: var(--er-radius); }

  /* Pagination */
  .er-pagination { display: flex; gap: 6px; margin-top: 16px; }
  .er-page-btn { background: var(--er-surface); border: 1px solid var(--er-border); padding: 5px 12px; font-family: var(--er-font); font-size: 13px; cursor: pointer; border-radius: var(--er-radius); }
  .er-page-btn.active { background: var(--er-primary); border-color: var(--er-primary); color: #fff; }

  /* Viewer */
  .er-viewer-meta { background: var(--er-surface); border: 1px solid var(--er-border); border-radius: var(--er-radius); padding: 20px; margin-bottom: 20px; }
  .er-meta-list { display: grid; grid-template-columns: max-content 1fr; gap: 6px 24px; font-size: 14px; }
  .er-meta-list dt { font-weight: 600; color: var(--er-muted); }
  .er-pdf-viewer { margin-bottom: 20px; border: 1px solid var(--er-border); border-radius: var(--er-radius); overflow: hidden; }
  .er-viewer-actions { display: flex; gap: 12px; align-items: center; }
  .er-viewer-empty { font-size: 14px; color: var(--er-muted); padding: 32px; text-align: center; background: var(--er-surface); border: 1px solid var(--er-border); border-radius: var(--er-radius); }

  /* How-to guides */
  .er-intro { font-size: 14px; color: var(--er-muted); margin-bottom: 20px; }
  .er-guide-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 16px; }
  .er-guide-card { background: var(--er-surface); border: 1px solid var(--er-border); border-radius: var(--er-radius); padding: 18px; }
  .er-guide-card h3 { font-size: 14px; font-weight: 700; margin-bottom: 6px; color: var(--er-primary); }
  .er-guide-card p { font-size: 13px; color: var(--er-muted); margin-bottom: 12px; }
  .er-guide-link { font-size: 13px; color: var(--er-primary); text-decoration: underline; }

  /* Fee table */
  .er-fee-table { max-width: 600px; margin-bottom: 24px; }
  .er-fee-notes { background: var(--er-surface); border: 1px solid var(--er-border); border-radius: var(--er-radius); padding: 20px; max-width: 600px; }
  .er-fee-notes h3 { font-size: 14px; font-weight: 700; margin-bottom: 10px; }
  .er-fee-notes ul { padding-left: 20px; font-size: 13px; color: var(--er-muted); display: flex; flex-direction: column; gap: 4px; }

  /* Buttons */
  .er-btn-primary { background: var(--er-primary); color: #fff; border: none; padding: 9px 20px; border-radius: var(--er-radius); font-family: var(--er-font); font-size: 14px; font-weight: 600; cursor: pointer; text-decoration: none; display: inline-block; }
  .er-btn-primary:hover { background: var(--er-primary-hover); }
  .er-btn-secondary { background: var(--er-surface); color: var(--er-text); border: 1px solid var(--er-border); padding: 9px 20px; border-radius: var(--er-radius); font-family: var(--er-font); font-size: 14px; cursor: pointer; text-decoration: none; display: inline-block; }
  .er-btn-secondary:hover { background: var(--er-bg); }

  /* Footer */
  .er-footer { background: var(--er-primary); color: rgba(255,255,255,0.8); text-align: center; padding: 16px 24px; font-size: 12px; }
</style>
