// src/components/l2/news/solid/NewsApp.tsx
/**
 * @qscrape L2 / solid / news
 * @component NewsApp
 */

import type { JSX } from 'solid-js';
import {
	createSignal,
	For,
	Match,
	onCleanup,
	onMount,
	Show,
	Switch,
} from 'solid-js';
import { fakeGet } from '../../../../data/api';
import type { ArticleMeta } from '../../../../data/news/articles';
import {
	articles,
	categories,
	formatDate,
	formatDateTime,
	getBreaking,
	getByCategory,
	getLatest,
	reporters,
} from '../../../../data/news/articles';
import '../../../../styles/l2/news.css';
import styles from '../../react/news/NewsApp.module.css';

// ── URL routing helpers ──────────────────────────────────────────────────────

function getBase(): string {
	return (
		'/' +
		window.location.pathname.split('/').filter(Boolean).slice(0, 3).join('/') +
		'/'
	);
}

function pathToState(): { page: Page; articleId?: string; category?: string } {
	const seg = window.location.pathname.split('/').filter(Boolean).at(-1) ?? '';
	const p = new URLSearchParams(window.location.search);
	if (seg === 'article') {
		return { page: 'article', articleId: p.get('id') ?? undefined };
	}
	if (seg === 'articles') {
		return { page: 'articles', category: p.get('cat') ?? undefined };
	}
	if (seg === 'about') {
		return { page: 'about' };
	}
	if (seg === 'staff') {
		return { page: 'staff' };
	}
	if (seg === 'contact') {
		return { page: 'contact' };
	}
	return { page: 'home' };
}

function pageToPath(p: Page, extra?: string): string {
	const base = getBase();
	if (p === 'article') {
		return `${base}article${extra ? `?id=${extra}` : ''}`;
	}
	if (p === 'articles') {
		return `${base}articles${extra ? `?cat=${encodeURIComponent(extra)}` : ''}`;
	}
	if (p === 'about') {
		return `${base}about`;
	}
	if (p === 'staff') {
		return `${base}staff`;
	}
	if (p === 'contact') {
		return `${base}contact`;
	}
	return base;
}

type Page = 'home' | 'articles' | 'article' | 'about' | 'contact' | 'staff';

function CategoryBadge(props: { category: string }) {
	return (
		<span
			class={`${styles.badge} ${styles[`badge_${props.category.toLowerCase()}`]}`}
		>
			{props.category}
		</span>
	);
}

function ArticleCard(props: {
	article: ArticleMeta;
	onNavigate: (id: string) => void;
}) {
	return (
		<article
			class={styles.articleCard}
			data-article-id={props.article.id}
			data-category={props.article.category}
		>
			<button
				type="button"
				class={styles.articleCardImg}
				onClick={() => props.onNavigate(props.article.id)}
			>
				<img
					src={props.article.image}
					alt={props.article.imageCaption}
					loading="lazy"
					width="580"
					height="320"
				/>
				<Show when={props.article.breaking}>
					<span class={styles.breakingTag}>BREAKING</span>
				</Show>
			</button>
			<div class={styles.articleCardBody}>
				<CategoryBadge category={props.article.category} />
				<h2 class={styles.articleCardHeadline}>
					<button
						type="button"
						onClick={() => props.onNavigate(props.article.id)}
					>
						{props.article.headline}
					</button>
				</h2>
				<p class={styles.articleCardExcerpt}>{props.article.excerpt}</p>
				<div class={styles.articleCardMeta}>
					<span class={styles.author}>{props.article.author}</span>
					<span class={styles.date}>{formatDate(props.article.published)}</span>
				</div>
			</div>
		</article>
	);
}

function HeraldShell(props: {
	children: JSX.Element;
	activePage: Page;
	onNavigate: (page: Page, extra?: string) => void;
}) {
	const breaking = getBreaking();
	return (
		<div class={styles.shell}>
			<header class={styles.masthead}>
				<div class={styles.mastheadInner}>
					<div class={styles.mastheadDate}>
						{new Date().toLocaleDateString('en-US', {
							weekday: 'long',
							year: 'numeric',
							month: 'long',
							day: 'numeric',
						})}
					</div>
					<button
						type="button"
						class={styles.mastheadTitle}
						onClick={() => props.onNavigate('home')}
					>
						<span class={styles.mastheadTitleMain}>
							The Mountainhome Herald
						</span>
						<span class={styles.mastheadTagline}>
							Est. Year 89 · Mountainhome, Granite Flats
						</span>
					</button>
					<div class={styles.mastheadRight}>
						&ldquo;All the news from Z-Level 1 to 120&rdquo;
					</div>
				</div>
				<Show when={breaking.length > 0}>
					<div class={styles.breakingBar}>
						<span class={styles.breakingLabel}>BREAKING</span>
						<div class={styles.breakingTicker}>
							<For each={breaking}>
								{(a, i) => (
									<span>
										{i() > 0 && ' · '}
										<button
											type="button"
											onClick={() => props.onNavigate('article', a.id)}
										>
											{a.headline}
										</button>
									</span>
								)}
							</For>
						</div>
					</div>
				</Show>
			</header>
			<nav class={styles.siteNav}>
				<div class={styles.siteNavInner}>
					<For
						each={['home', 'articles', 'about', 'staff', 'contact'] as Page[]}
					>
						{(p) => (
							<button
								type="button"
								class={`${styles.navItem} ${props.activePage === p ? styles.navItemActive : ''}`}
								onClick={() => props.onNavigate(p)}
							>
								{p === 'home' ? 'Home' : p.charAt(0).toUpperCase() + p.slice(1)}
							</button>
						)}
					</For>
				</div>
			</nav>
			<main class={styles.main}>{props.children}</main>
			<footer class={styles.footer}>
				<div class={styles.footerInner}>
					<p>&copy; Year 312 The Mountainhome Herald. All rights reserved.</p>
					<p class={styles.footerLinks}>
						<button type="button" onClick={() => props.onNavigate('about')}>
							About
						</button>
						{' · '}
						<button type="button" onClick={() => props.onNavigate('contact')}>
							Contact
						</button>
						{' · '}
						<button type="button" onClick={() => props.onNavigate('staff')}>
							Staff
						</button>
					</p>
				</div>
			</footer>
		</div>
	);
}

function HomePage(props: { onNavigate: (page: Page, extra?: string) => void }) {
	const latest = getLatest(20);
	const featured = latest[0];
	const grid = latest.slice(1, 7);
	const sidebar = latest.slice(7, 13);

	return (
		<div class={styles.homePage}>
			<Show when={featured}>
				<section class={styles.hero}>
					<button
						type="button"
						class={styles.heroImg}
						onClick={() => props.onNavigate('article', featured!.id)}
					>
						<img
							src={featured!.image}
							alt={featured!.imageCaption}
							width="900"
							height="500"
							loading="eager"
						/>
						<Show when={featured!.breaking}>
							<span class={styles.breakingTag}>BREAKING</span>
						</Show>
					</button>
					<div class={styles.heroBody}>
						<CategoryBadge category={featured!.category} />
						<h1 class={styles.heroHeadline}>
							<button
								type="button"
								onClick={() => props.onNavigate('article', featured!.id)}
							>
								{featured!.headline}
							</button>
						</h1>
						<p class={styles.heroExcerpt}>{featured!.excerpt}</p>
						<div class={styles.heroMeta}>
							<span>{featured!.author}</span>
							<span>{formatDateTime(featured!.published)}</span>
						</div>
					</div>
				</section>
			</Show>
			<div class={styles.homeLayout}>
				<section class={styles.articleGrid}>
					<h2 class={styles.sectionHead}>Latest News</h2>
					<div class={styles.grid3}>
						<For each={grid}>
							{(a) => (
								<ArticleCard
									article={a}
									onNavigate={(id) => props.onNavigate('article', id)}
								/>
							)}
						</For>
					</div>
					<button
						type="button"
						class={styles.moreBtn}
						onClick={() => props.onNavigate('articles')}
					>
						More Stories →
					</button>
				</section>
				<aside class={styles.sidebar}>
					<div class={styles.sideWidget}>
						<h3 class={styles.sideWidgetTitle}>Top Stories</h3>
						<For each={sidebar}>
							{(a) => (
								<div class={styles.sideItem}>
									<CategoryBadge category={a.category} />
									<button
										type="button"
										class={styles.sideItemHead}
										onClick={() => props.onNavigate('article', a.id)}
									>
										{a.headline}
									</button>
									<div class={styles.sideItemMeta}>
										{formatDate(a.published)}
									</div>
								</div>
							)}
						</For>
					</div>
					<div class={styles.sideWidget}>
						<h3 class={styles.sideWidgetTitle}>Sections</h3>
						<For each={categories}>
							{(cat) => (
								<button
									type="button"
									class={styles.sideCategory}
									onClick={() => props.onNavigate('articles')}
								>
									{cat}
								</button>
							)}
						</For>
					</div>
				</aside>
			</div>
		</div>
	);
}

function ArticlesPage(props: {
	onNavigate: (page: Page, extra?: string) => void;
	initialCategory?: string;
}) {
	const [activeCategory, setActiveCategory] = createSignal(
		props.initialCategory || 'All',
	);
	const [page, setPage] = createSignal(1);
	const PER_PAGE = 6;

	const filtered = () =>
		activeCategory() === 'All' ? articles : getByCategory(activeCategory());
	const totalPages = () => Math.ceil(filtered().length / PER_PAGE);
	const pageItems = () =>
		filtered().slice((page() - 1) * PER_PAGE, page() * PER_PAGE);

	return (
		<div class={styles.articlesPage}>
			<h1 class={styles.pageTitle}>Articles</h1>
			<div class={styles.filterTabs}>
				<For each={['All', ...categories]}>
					{(cat) => (
						<button
							type="button"
							class={`${styles.filterTab} ${activeCategory() === cat ? styles.filterTabActive : ''}`}
							onClick={() => {
								setActiveCategory(cat);
								setPage(1);
							}}
							data-category={cat}
						>
							{cat}
						</button>
					)}
				</For>
			</div>
			<div class={styles.grid3}>
				<For each={pageItems()}>
					{(a) => (
						<ArticleCard
							article={a}
							onNavigate={(id) => props.onNavigate('article', id)}
						/>
					)}
				</For>
			</div>
			<Show when={totalPages() > 1}>
				<div class={styles.pagination}>
					<For each={Array.from({ length: totalPages() }, (_, i) => i + 1)}>
						{(p) => (
							<button
								type="button"
								class={`${styles.pageBtn} ${p === page() ? styles.pageBtnActive : ''}`}
								onClick={() => setPage(p)}
							>
								{p}
							</button>
						)}
					</For>
				</div>
			</Show>
		</div>
	);
}

function ArticlePage(props: {
	articleId: string;
	onNavigate: (page: Page, extra?: string) => void;
}) {
	const article = () => articles.find((a) => a.id === props.articleId);
	const related = () =>
		articles
			.filter(
				(a) => a.category === article()?.category && a.id !== props.articleId,
			)
			.slice(0, 3);

	return (
		<Show
			when={article()}
			fallback={
				<div class={styles.notFound}>
					<h1>Article not found</h1>
					<button type="button" onClick={() => props.onNavigate('home')}>
						← Home
					</button>
				</div>
			}
		>
			{(art) => (
				<div class={styles.articlePage}>
					<div class={styles.articleReading}>
						<nav class={styles.breadcrumb}>
							<button type="button" onClick={() => props.onNavigate('home')}>
								Home
							</button>
							{' / '}
							<button
								type="button"
								onClick={() => props.onNavigate('articles')}
							>
								{art().category}
							</button>
						</nav>
						<CategoryBadge category={art().category} />
						<Show when={art().breaking}>
							<span class={`${styles.breakingTag} ${styles.breakingTagInline}`}>
								BREAKING
							</span>
						</Show>
						<h1 class={styles.articleHeadline}>{art().headline}</h1>
						<div class={styles.articleByline}>
							<span class={styles.author}>{art().author}</span>
							<span class={styles.bylineTitle}>{art().byline}</span>
							<time dateTime={art().published} class={styles.date}>
								{formatDateTime(art().published)}
							</time>
							<Show when={art().updated}>
								<span class={styles.updated}>
									Updated: {formatDateTime(art().updated!)}
								</span>
							</Show>
						</div>
						<figure class={styles.articleFigure}>
							<img
								src={art().image}
								alt={art().imageCaption}
								width="680"
								height="380"
							/>
							<figcaption>
								<span>{art().imageCaption}</span>
								<span class={styles.credit}> {art().imageCredit}</span>
							</figcaption>
						</figure>
						<div class={styles.articleBody}>
							<p class={styles.articleLead}>{art().excerpt}</p>
							<p>
								The Mountainhome Herald continues to follow developments related
								to this story. This report will be updated as additional
								information becomes available from official sources and
								correspondents in the field.
							</p>
							<p>
								Residents and stakeholders with relevant information are
								encouraged to contact the Herald editorial desk at{' '}
								<em>editor@herald.mh</em>. The Herald is committed to accurate,
								thorough coverage of all matters affecting the citizens of
								Mountainhome and the broader Granite Flats sector.
							</p>
						</div>
						<Show when={art().tags.length > 0}>
							<div class={styles.articleTags}>
								<For each={art().tags}>
									{(tag) => <span class={styles.tag}>{tag}</span>}
								</For>
							</div>
						</Show>
						<Show when={related().length > 0}>
							<aside class={styles.relatedArticles}>
								<h2 class={styles.relatedTitle}>Related Articles</h2>
								<div class={styles.relatedGrid}>
									<For each={related()}>
										{(r) => (
											<ArticleCard
												article={r}
												onNavigate={(id) => props.onNavigate('article', id)}
											/>
										)}
									</For>
								</div>
							</aside>
						</Show>
					</div>
				</div>
			)}
		</Show>
	);
}

function AboutPage() {
	return (
		<div class={styles.staticPage}>
			<h1 class={styles.pageTitle}>About the Herald</h1>
			<div class={styles.staticBody}>
				<p>
					The Mountainhome Herald was founded in Year 89 by Master Scribe Urist
					Bookbinder as a single-page broadsheet distributed weekly to fortress
					residents and guild officials. Over more than two centuries it has
					grown into the fortress's newspaper of record.
				</p>
				<h2>Editorial Policy</h2>
				<p>
					The Herald is committed to factual, impartial reporting on all matters
					affecting the citizens of Mountainhome. Our editorial staff
					independently verifies all claims before publication. Corrections are
					published promptly when errors are identified.
				</p>
				<h2>Coverage Areas</h2>
				<p>
					The Herald covers Politics, Crime, Economy, Culture, Sports, and
					Weather across all z-levels from the surface to the magma sea sector
					at Z-Level 114.
				</p>
				<h2>Subscriptions</h2>
				<p>
					Physical broadsheet delivery is available to all registered fortress
					residences. Contact the circulation desk for rates.
				</p>
			</div>
		</div>
	);
}

function StaffPage() {
	return (
		<div class={styles.staticPage}>
			<h1 class={styles.pageTitle}>Editorial Staff</h1>
			<div class={styles.staffGrid}>
				<For each={reporters}>
					{(r) => (
						<div class={styles.staffCard}>
							<div class={styles.staffName}>{r.name}</div>
							<div class={styles.staffTitle}>{r.title}</div>
							<div class={styles.staffBeat}>{r.beat}</div>
							<a href={`mailto:${r.email}`} class={styles.staffEmail}>
								{r.email}
							</a>
						</div>
					)}
				</For>
			</div>
		</div>
	);
}

function ContactPage() {
	return (
		<div class={styles.staticPage}>
			<h1 class={styles.pageTitle}>Contact the Herald</h1>
			<div class={styles.staticBody}>
				<h2>Editorial</h2>
				<p>
					General editorial inquiries:{' '}
					<a href="mailto:editor@herald.mh">editor@herald.mh</a>
				</p>
				<p>
					Tips and story leads:{' '}
					<a href="mailto:tips@herald.mh">tips@herald.mh</a>
				</p>
				<h2>Advertising</h2>
				<p>
					Display and classified advertising:{' '}
					<a href="mailto:advertising@herald.mh">advertising@herald.mh</a>
				</p>
				<p>
					Rate card available upon request. Herald reaches approximately 4,200
					fortress residents weekly.
				</p>
				<h2>Subscriptions</h2>
				<p>
					Circulation desk:{' '}
					<a href="mailto:circulation@herald.mh">circulation@herald.mh</a>
				</p>
				<p>
					Physical address: Herald Tower, Z-Level 3, Mountainhome Civic Quarter
				</p>
			</div>
		</div>
	);
}

export default function NewsApp(props: {
	initialPage?: Page;
	initialArticleId?: string;
	initialCategory?: string;
}) {
	const [ready, setReady] = createSignal(false);
	const [page, setPage] = createSignal<Page>(props.initialPage || 'home');
	const [articleId, setArticleId] = createSignal<string | undefined>(
		props.initialArticleId,
	);

	onMount(() => {
		const { page: urlPage, articleId: urlId } = pathToState();
		setPage(urlPage);
		if (urlId) {
			setArticleId(urlId);
		}

		fakeGet(null).then(() => setReady(true));

		const onPop = () => {
			const s = pathToState();
			setPage(s.page);
			if (s.articleId) {
				setArticleId(s.articleId);
			}
			window.scrollTo(0, 0);
		};
		window.addEventListener('popstate', onPop);
		onCleanup(() => window.removeEventListener('popstate', onPop));
	});

	const navigate = (p: Page, extra?: string) => {
		setPage(p);
		if (p === 'article' && extra) {
			setArticleId(extra);
		}
		history.pushState(null, '', pageToPath(p, extra));
		window.scrollTo(0, 0);
	};

	return (
		<Show
			when={ready()}
			fallback={
				<div
					style={{
						display: 'flex',
						'align-items': 'center',
						'justify-content': 'center',
						'min-height': '100vh',
						'font-family': 'Georgia,serif',
						color: '#666',
					}}
				>
					Loading…
				</div>
			}
		>
			<HeraldShell activePage={page()} onNavigate={navigate}>
				<Switch>
					<Match when={page() === 'home'}>
						<HomePage onNavigate={navigate} />
					</Match>
					<Match when={page() === 'articles'}>
						<ArticlesPage
							onNavigate={navigate}
							initialCategory={props.initialCategory}
						/>
					</Match>
					<Match when={page() === 'article'}>
						<ArticlePage articleId={articleId() || ''} onNavigate={navigate} />
					</Match>
					<Match when={page() === 'about'}>
						<AboutPage />
					</Match>
					<Match when={page() === 'staff'}>
						<StaffPage />
					</Match>
					<Match when={page() === 'contact'}>
						<ContactPage />
					</Match>
					<Match when={true}>
						<HomePage onNavigate={navigate} />
					</Match>
				</Switch>
			</HeraldShell>
		</Show>
	);
}

// src/components/l2/news/vue/NewsApp.vue
<!-- @qscrape L2 / vue / news -->
<!-- @component NewsApp -->
<template>
  <div v-if="!ready" style="display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:Georgia,serif;color:#666">Loading…</div>
  <div v-else class="hn-shell">
    <!-- Masthead -->
    <header class="hn-masthead">
      <div class="hn-masthead-inner">
        <div class="hn-masthead-date">{{ currentDate }}</div>
        <button class="hn-masthead-title" @click="navigate('home')">
          <span class="hn-masthead-main">The Mountainhome Herald</span>
          <span class="hn-masthead-tag">Est. Year 89 · Mountainhome, Granite Flats</span>
        </button>
        <div class="hn-masthead-right">&ldquo;All the news from Z-Level 1 to 120&rdquo;</div>
      </div>
      <div v-if="breaking.length" class="hn-breaking-bar">
        <span class="hn-breaking-label">BREAKING</span>
        <div class="hn-breaking-ticker">
          <template v-for="(a, i) in breaking" :key="a.id">
            <span v-if="i > 0"> · </span>
            <a @click="navigate('article', a.id)">{{ a.headline }}</a>
          </template>
        </div>
      </div>
    </header>

    <!-- Nav -->
    <nav class="hn-nav">
      <div class="hn-nav-inner">
        <button v-for="p in navPages" :key="p.id"
          :class="['hn-nav-item', { 'hn-nav-item--active': page === p.id }]"
          @click="navigate(p.id)">{{ p.label }}</button>
      </div>
    </nav>

    <!-- Home -->
    <main class="hn-main" v-if="page === 'home'">
      <section class="hn-hero" v-if="featured">
        <a class="hn-hero-img" @click="navigate('article', featured.id)">
          <img :src="featured.image" width="900" height="500" loading="eager" />
          <span v-if="featured.breaking" class="hn-breaking-tag">BREAKING</span>
        </a>
        <div class="hn-hero-body">
          <span :class="['hn-badge', 'hn-badge--' + featured.category.toLowerCase()]">{{ featured.category }}</span>
          <h1 class="hn-hero-hl">
            <a @click="navigate('article', featured.id)">{{ featured.headline }}</a>
          </h1>
          <p class="hn-hero-exc">{{ featured.excerpt }}</p>
          <div class="hn-hero-meta">
            <span>{{ featured.author }}</span>
            <span>{{ formatDateTime(featured.published) }}</span>
          </div>
        </div>
      </section>

      <div class="hn-home-layout">
        <section class="hn-article-grid">
          <h2 class="hn-section-head">Latest News</h2>
          <div class="hn-grid3">
            <article v-for="a in gridArticles" :key="a.id" class="hn-article-card" :data-article-id="a.id" :data-category="a.category">
              <a class="hn-card-img" @click="navigate('article', a.id)">
                <img :src="a.image" loading="lazy" width="580" height="320" />
                <span v-if="a.breaking" class="hn-breaking-tag">BREAKING</span>
              </a>
              <div class="hn-card-body">
                <span :class="['hn-badge', 'hn-badge--' + a.category.toLowerCase()]">{{ a.category }}</span>
                <h2 class="hn-card-hl">
                  <a @click="navigate('article', a.id)">{{ a.headline }}</a>
                </h2>
                <p class="hn-card-exc">{{ a.excerpt }}</p>
                <div class="hn-card-meta">
                  <span>{{ a.author }}</span>
                  <span>{{ formatDate(a.published) }}</span>
                </div>
              </div>
            </article>
          </div>
          <button class="hn-more-btn" @click="navigate('articles')">More Stories →</button>
        </section>

        <aside class="hn-sidebar">
          <div class="hn-side-widget">
            <h3 class="hn-side-title">Top Stories</h3>
            <div v-for="a in sidebarArticles" :key="a.id" class="hn-side-item">
              <span :class="['hn-badge', 'hn-badge--' + a.category.toLowerCase()]">{{ a.category }}</span>
              <a class="hn-side-hl" @click="navigate('article', a.id)">{{ a.headline }}</a>
              <div class="hn-side-date">{{ formatDate(a.published) }}</div>
            </div>
          </div>
          <div class="hn-side-widget">
            <h3 class="hn-side-title">Sections</h3>
            <button v-for="cat in categories" :key="cat" class="hn-side-cat" @click="navigate('articles')">{{ cat }}</button>
          </div>
        </aside>
      </div>
    </main>

    <!-- Articles -->
    <main class="hn-main" v-else-if="page === 'articles'">
      <h1 class="hn-page-title">Articles</h1>
      <div class="hn-filter-tabs">
        <button v-for="cat in ['All', ...categories]" :key="cat"
          :class="['hn-filter-tab', { 'hn-filter-tab--active': activeCategory === cat }]"
          :data-category="cat"
          @click="setCategory(cat)">{{ cat }}</button>
      </div>
      <div class="hn-grid3">
        <article v-for="a in pagedArticles" :key="a.id" class="hn-article-card" :data-article-id="a.id" :data-category="a.category">
          <a class="hn-card-img" @click="navigate('article', a.id)">
            <img :src="a.image" loading="lazy" width="580" height="320" />
            <span v-if="a.breaking" class="hn-breaking-tag">BREAKING</span>
          </a>
          <div class="hn-card-body">
            <span :class="['hn-badge', 'hn-badge--' + a.category.toLowerCase()]">{{ a.category }}</span>
            <h2 class="hn-card-hl">
              <a @click="navigate('article', a.id)">{{ a.headline }}</a>
            </h2>
            <p class="hn-card-exc">{{ a.excerpt }}</p>
            <div class="hn-card-meta">
              <span>{{ a.author }}</span>
              <span>{{ formatDate(a.published) }}</span>
            </div>
          </div>
        </article>
      </div>
      <div v-if="totalArticlePages > 1" class="hn-pagination">
        <button v-for="p in totalArticlePages" :key="p"
          :class="['hn-page-btn', { 'hn-page-btn--active': articlePage === p }]"
          @click="articlePage = p">{{ p }}</button>
      </div>
    </main>

    <!-- Article detail -->
    <main class="hn-main" v-else-if="page === 'article'">
      <div v-if="currentArticle" class="hn-reading">
        <nav class="hn-breadcrumb">
          <button @click="navigate('home')">Home</button>
          /
          <button @click="navigate('articles')">{{ currentArticle.category }}</button>
        </nav>
        <span :class="['hn-badge', 'hn-badge--' + currentArticle.category.toLowerCase()]">{{ currentArticle.category }}</span>
        <span v-if="currentArticle.breaking" class="hn-breaking-tag hn-breaking-tag--inline">BREAKING</span>
        <h1 class="hn-article-hl">{{ currentArticle.headline }}</h1>
        <div class="hn-article-byline">
          <span class="hn-author">{{ currentArticle.author }}</span>
          <span class="hn-byline-title">{{ currentArticle.byline }}</span>
          <time :datetime="currentArticle.published">{{ formatDateTime(currentArticle.published) }}</time>
          <span v-if="currentArticle.updated" class="hn-updated">Updated: {{ formatDateTime(currentArticle.updated) }}</span>
        </div>
        <figure class="hn-article-fig">
          <img :src="currentArticle.image" width="680" height="380" />
          <figcaption>{{ currentArticle.imageCaption }} <em>{{ currentArticle.imageCredit }}</em></figcaption>
        </figure>
        <div class="hn-article-body">
          <p class="hn-article-lead">{{ currentArticle.excerpt }}</p>
          <p>The Mountainhome Herald continues to follow developments related to this story. This report will be updated as additional information becomes available from official sources and correspondents in the field.</p>
          <p>Residents and stakeholders with relevant information are encouraged to contact the Herald editorial desk at <em>editor@herald.mh</em>.</p>
        </div>
        <div class="hn-article-tags">
          <span v-for="tag in currentArticle.tags" :key="tag" class="hn-tag">{{ tag }}</span>
        </div>
        <aside v-if="relatedArticles.length" class="hn-related">
          <h2 class="hn-related-title">Related Articles</h2>
          <div class="hn-grid3">
            <article v-for="a in relatedArticles" :key="a.id" class="hn-article-card" :data-article-id="a.id">
              <a class="hn-card-img" @click="navigate('article', a.id)">
                <img :src="a.image" loading="lazy" width="580" height="320" />
              </a>
              <div class="hn-card-body">
                <span :class="['hn-badge', 'hn-badge--' + a.category.toLowerCase()]">{{ a.category }}</span>
                <h2 class="hn-card-hl"><a @click="navigate('article', a.id)">{{ a.headline }}</a></h2>
                <div class="hn-card-meta"><span>{{ a.author }}</span><span>{{ formatDate(a.published) }}</span></div>
              </div>
            </article>
          </div>
        </aside>
      </div>
      <div v-else class="hn-not-found">
        <h1>Article not found</h1>
        <button @click="navigate('home')">← Home</button>
      </div>
    </main>

    <!-- About -->
    <main class="hn-main hn-static-page" v-else-if="page === 'about'">
      <h1 class="hn-page-title">About the Herald</h1>
      <div class="hn-static-body">
        <p>The Mountainhome Herald was founded in Year 89 by Master Scribe Urist Bookbinder as a single-page broadsheet. Over more than two centuries it has grown into the fortress's newspaper of record.</p>
        <h2>Editorial Policy</h2>
        <p>The Herald is committed to factual, impartial reporting on all matters affecting the citizens of Mountainhome. Our editorial staff independently verifies all claims before publication.</p>
        <h2>Coverage Areas</h2>
        <p>The Herald covers Politics, Crime, Economy, Culture, Sports, and Weather across all z-levels from the surface to Z-Level 114.</p>
      </div>
    </main>

    <!-- Staff -->
    <main class="hn-main" v-else-if="page === 'staff'">
      <h1 class="hn-page-title">Editorial Staff</h1>
      <div class="hn-staff-grid">
        <div v-for="r in reporters" :key="r.email" class="hn-staff-card">
          <div class="hn-staff-name">{{ r.name }}</div>
          <div class="hn-staff-title">{{ r.title }}</div>
          <div class="hn-staff-beat">{{ r.beat }}</div>
          <a :href="'mailto:' + r.email" class="hn-staff-email">{{ r.email }}</a>
        </div>
      </div>
    </main>

    <!-- Contact -->
    <main class="hn-main hn-static-page" v-else-if="page === 'contact'">
      <h1 class="hn-page-title">Contact the Herald</h1>
      <div class="hn-static-body">
        <h2>Editorial</h2>
        <p>General inquiries: <a href="mailto:editor@herald.mh">editor@herald.mh</a></p>
        <p>Tips and story leads: <a href="mailto:tips@herald.mh">tips@herald.mh</a></p>
        <h2>Advertising</h2>
        <p>Display and classified advertising: <a href="mailto:advertising@herald.mh">advertising@herald.mh</a></p>
        <h2>Subscriptions</h2>
        <p>Circulation desk: <a href="mailto:circulation@herald.mh">circulation@herald.mh</a></p>
      </div>
    </main>

    <!-- Footer -->
    <footer class="hn-footer">
      <div class="hn-footer-inner">
        <p>&copy; Year 312 The Mountainhome Herald.</p>
        <p class="hn-footer-links">
          <a @click="navigate('about')">About</a> ·
          <a @click="navigate('contact')">Contact</a> ·
          <a @click="navigate('staff')">Staff</a>
        </p>
      </div>
    </footer>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { fakeGet } from '../../../../data/api';
import {
	articles,
	getBreaking,
	getByCategory,
	getLatest,
} from '../../../../data/news/articles';

type Page = 'home' | 'articles' | 'article' | 'about' | 'contact' | 'staff';

// ── URL routing helpers ────────────────────────────────────────────────────
function getBase() {
	return `/${window.location.pathname.split('/').filter(Boolean).slice(0, 3).join('/')}/`;
}
function pathToState() {
	const seg = window.location.pathname.split('/').filter(Boolean).at(-1) ?? '';
	const p = new URLSearchParams(window.location.search);
	if (seg === 'article') {
		return { page: 'article' as Page, id: p.get('id') ?? '' };
	}
	if (seg === 'articles') {
		return { page: 'articles' as Page, id: '' };
	}
	if (seg === 'about') {
		return { page: 'about' as Page, id: '' };
	}
	if (seg === 'staff') {
		return { page: 'staff' as Page, id: '' };
	}
	if (seg === 'contact') {
		return { page: 'contact' as Page, id: '' };
	}
	return { page: 'home' as Page, id: '' };
}
function pageToPath(p: Page, id?: string) {
	const base = getBase();
	if (p === 'article') {
		return `${base}article${id ? `?id=${id}` : ''}`;
	}
	if (p === 'articles') {
		return `${base}articles`;
	}
	if (p === 'about') {
		return `${base}about`;
	}
	if (p === 'staff') {
		return `${base}staff`;
	}
	if (p === 'contact') {
		return `${base}contact`;
	}
	return base;
}

const ready = ref(false);
const page = ref<Page>('home');
const currentId = ref('');
const activeCategory = ref('All');
const articlePage = ref(1);
const PER_PAGE = 6;

const _currentDate = new Date().toLocaleDateString('en-US', {
	weekday: 'long',
	year: 'numeric',
	month: 'long',
	day: 'numeric',
});
const _breaking = getBreaking();
const _navPages = [
	{ id: 'home' as Page, label: 'Home' },
	{ id: 'articles' as Page, label: 'Articles' },
	{ id: 'about' as Page, label: 'About' },
	{ id: 'staff' as Page, label: 'Staff' },
	{ id: 'contact' as Page, label: 'Contact' },
];

const latest = getLatest(20);
const _featured = computed(() => latest[0]);
const _gridArticles = computed(() => latest.slice(1, 7));
const _sidebarArticles = computed(() => latest.slice(7, 13));

const filteredArticles = computed(() =>
	activeCategory.value === 'All'
		? articles
		: getByCategory(activeCategory.value),
);
const _totalArticlePages = computed(() =>
	Math.ceil(filteredArticles.value.length / PER_PAGE),
);
const _pagedArticles = computed(() =>
	filteredArticles.value.slice(
		(articlePage.value - 1) * PER_PAGE,
		articlePage.value * PER_PAGE,
	),
);

const currentArticle = computed(() =>
	articles.find((a) => a.id === currentId.value),
);
const _relatedArticles = computed(() =>
	currentArticle.value
		? articles
				.filter(
					(a) =>
						a.category === currentArticle.value?.category &&
						a.id !== currentId.value,
				)
				.slice(0, 3)
		: [],
);

function _navigate(p: Page, id?: string) {
	page.value = p;
	if (id) {
		currentId.value = id;
	}
	history.pushState(null, '', pageToPath(p, id));
	window.scrollTo(0, 0);
}

function _setCategory(cat: string) {
	activeCategory.value = cat;
	articlePage.value = 1;
}

function onPop() {
	const s = pathToState();
	page.value = s.page;
	currentId.value = s.id;
	window.scrollTo(0, 0);
}

onMounted(() => {
	const s = pathToState();
	page.value = s.page;
	currentId.value = s.id;
	window.addEventListener('popstate', onPop);
	fakeGet(null).then(() => {
		ready.value = true;
	});
});
onUnmounted(() => window.removeEventListener('popstate', onPop));
</script>

<style scoped>
.hn-shell { min-height: 100vh; background: #fafaf8; color: #1a1a1a; font-family: 'Lora', Georgia, serif; }

/* Masthead */
.hn-masthead { background: #1a1a1a; color: #fff; }
.hn-masthead-inner { max-width: 1100px; margin: 0 auto; padding: 16px 24px; display: grid; grid-template-columns: 1fr auto 1fr; align-items: center; gap: 16px; }
.hn-masthead-date { font-family: system-ui, sans-serif; font-size: 12px; color: #aaa; }
.hn-masthead-title { background: none; border: none; cursor: pointer; text-align: center; color: #fff; padding: 0; }
.hn-masthead-main { display: block; font-family: 'Playfair Display', Georgia, serif; font-size: clamp(24px, 4vw, 42px); font-weight: 700; line-height: 1.1; }
.hn-masthead-tag { display: block; font-size: 11px; color: #aaa; margin-top: 4px; letter-spacing: 0.05em; text-transform: uppercase; }
.hn-masthead-right { font-size: 12px; color: #aaa; text-align: right; font-style: italic; font-family: system-ui, sans-serif; }
.hn-breaking-bar { background: #c0392b; display: flex; align-items: center; gap: 12px; padding: 6px 24px; font-family: system-ui, sans-serif; font-size: 13px; }
.hn-breaking-label { font-weight: 700; color: #fff; white-space: nowrap; letter-spacing: 0.08em; }
.hn-breaking-ticker { color: #fff; }
.hn-breaking-ticker a { color: #fff; cursor: pointer; }
.hn-breaking-ticker a:hover { text-decoration: underline; }

/* Nav */
.hn-nav { border-bottom: 2px solid #c0392b; background: #fff; }
.hn-nav-inner { max-width: 1100px; margin: 0 auto; padding: 0 24px; display: flex; }
.hn-nav-item { background: none; border: none; cursor: pointer; padding: 12px 16px; font-family: system-ui, sans-serif; font-size: 14px; font-weight: 500; color: #1a1a1a; text-transform: uppercase; letter-spacing: 0.04em; border-bottom: 3px solid transparent; margin-bottom: -2px; }
.hn-nav-item:hover { border-bottom-color: #c0392b; color: #c0392b; }
.hn-nav-item--active { border-bottom-color: #c0392b; color: #c0392b; }

/* Main */
.hn-main { max-width: 1100px; margin: 0 auto; padding: 32px 24px; }

/* Badges */
.hn-badge { display: inline-block; font-family: system-ui, sans-serif; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; padding: 2px 8px; border-radius: 2px; margin-bottom: 8px; }
.hn-badge--politics { background: #dbeafe; color: #1e3a5f; }
.hn-badge--crime { background: #fee2e2; color: #7f1d1d; }
.hn-badge--economy { background: #dcfce7; color: #14532d; }
.hn-badge--culture { background: #ede9fe; color: #4c1d95; }
.hn-badge--sports { background: #ecfdf5; color: #065f46; }
.hn-badge--weather { background: #fef9c3; color: #713f12; }
.hn-breaking-tag { position: absolute; top: 10px; left: 10px; background: #c0392b; color: #fff; font-family: system-ui, sans-serif; font-size: 11px; font-weight: 700; padding: 3px 8px; }
.hn-breaking-tag--inline { position: static; display: inline-block; margin-left: 8px; vertical-align: middle; }

/* Hero */
.hn-hero { margin-bottom: 32px; }
.hn-hero-img { display: block; position: relative; cursor: pointer; }
.hn-hero-img img { width: 100%; aspect-ratio: 16/9; object-fit: cover; max-height: 500px; }
.hn-hero-body { padding: 20px 0; border-bottom: 1px solid #e5e5e5; }
.hn-hero-hl { font-family: 'Playfair Display', Georgia, serif; font-size: clamp(24px, 3vw, 36px); font-weight: 700; line-height: 1.2; margin-bottom: 12px; }
.hn-hero-hl a { color: #1a1a1a; cursor: pointer; }
.hn-hero-hl a:hover { color: #c0392b; text-decoration: none; }
.hn-hero-exc { font-size: 16px; color: #666; margin-bottom: 12px; }
.hn-hero-meta { display: flex; gap: 16px; font-family: system-ui, sans-serif; font-size: 13px; color: #666; }

/* Layout */
.hn-home-layout { display: grid; grid-template-columns: 1fr 280px; gap: 32px; }
.hn-grid3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; margin-bottom: 24px; }
@media (max-width: 900px) { .hn-grid3 { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 560px) { .hn-grid3 { grid-template-columns: 1fr; } }
.hn-section-head { font-family: 'Playfair Display', Georgia, serif; font-size: 22px; margin-bottom: 20px; border-bottom: 2px solid #c0392b; padding-bottom: 8px; }
.hn-more-btn { display: block; margin: 0 auto; background: none; border: 2px solid #c0392b; color: #c0392b; font-family: system-ui, sans-serif; font-size: 14px; font-weight: 600; padding: 10px 24px; cursor: pointer; text-transform: uppercase; letter-spacing: 0.05em; }
.hn-more-btn:hover { background: #c0392b; color: #fff; }

/* Article card */
.hn-article-card { background: #fff; border: 1px solid #e5e5e5; overflow: hidden; }
.hn-card-img { display: block; position: relative; cursor: pointer; }
.hn-card-img img { width: 100%; aspect-ratio: 16/9; object-fit: cover; }
.hn-card-body { padding: 16px; }
.hn-card-hl { font-family: 'Playfair Display', Georgia, serif; font-size: 18px; font-weight: 700; line-height: 1.3; margin-bottom: 8px; }
.hn-card-hl a { color: #1a1a1a; cursor: pointer; }
.hn-card-hl a:hover { color: #c0392b; text-decoration: none; }
.hn-card-exc { font-size: 14px; color: #666; margin-bottom: 12px; line-height: 1.5; }
.hn-card-meta { display: flex; justify-content: space-between; font-family: system-ui, sans-serif; font-size: 12px; color: #666; }

/* Sidebar */
.hn-sidebar { display: flex; flex-direction: column; gap: 24px; }
.hn-side-widget { background: #fff; border: 1px solid #e5e5e5; padding: 16px; }
.hn-side-title { font-family: 'Playfair Display', Georgia, serif; font-size: 16px; font-weight: 700; border-bottom: 2px solid #c0392b; padding-bottom: 8px; margin-bottom: 12px; }
.hn-side-item { margin-bottom: 14px; padding-bottom: 14px; border-bottom: 1px solid #e5e5e5; }
.hn-side-item:last-child { margin-bottom: 0; padding-bottom: 0; border-bottom: none; }
.hn-side-hl { display: block; font-size: 14px; font-family: 'Playfair Display', Georgia, serif; font-weight: 600; line-height: 1.4; cursor: pointer; color: #1a1a1a; }
.hn-side-hl:hover { color: #c0392b; }
.hn-side-date { font-family: system-ui, sans-serif; font-size: 11px; color: #666; margin-top: 4px; }
.hn-side-cat { display: block; width: 100%; background: none; border: none; text-align: left; cursor: pointer; padding: 6px 0; font-size: 14px; color: #1a1a1a; border-bottom: 1px solid #e5e5e5; font-family: 'Lora', Georgia, serif; }
.hn-side-cat:hover { color: #c0392b; }

/* Articles page */
.hn-page-title { font-family: 'Playfair Display', Georgia, serif; font-size: 32px; margin-bottom: 24px; }
.hn-filter-tabs { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 24px; }
.hn-filter-tab { background: none; border: 1px solid #e5e5e5; cursor: pointer; padding: 6px 14px; font-family: system-ui, sans-serif; font-size: 13px; color: #1a1a1a; }
.hn-filter-tab:hover { border-color: #c0392b; color: #c0392b; }
.hn-filter-tab--active { background: #c0392b; border-color: #c0392b; color: #fff; }
.hn-pagination { display: flex; justify-content: center; gap: 8px; margin-top: 32px; }
.hn-page-btn { background: none; border: 1px solid #e5e5e5; padding: 8px 14px; cursor: pointer; font-size: 14px; font-family: system-ui, sans-serif; color: #1a1a1a; }
.hn-page-btn:hover { border-color: #c0392b; color: #c0392b; }
.hn-page-btn--active { background: #c0392b; border-color: #c0392b; color: #fff; }

/* Article detail */
.hn-reading { max-width: 680px; margin: 0 auto; }
.hn-breadcrumb { font-family: system-ui, sans-serif; font-size: 13px; color: #666; margin-bottom: 20px; }
.hn-breadcrumb button { background: none; border: none; cursor: pointer; color: #666; font-size: 13px; }
.hn-breadcrumb button:hover { color: #c0392b; }
.hn-article-hl { font-family: 'Playfair Display', Georgia, serif; font-size: clamp(24px, 3vw, 36px); font-weight: 700; line-height: 1.2; margin: 12px 0; }
.hn-article-byline { display: flex; flex-wrap: wrap; gap: 8px 16px; font-family: system-ui, sans-serif; font-size: 13px; color: #666; margin-bottom: 20px; padding-bottom: 16px; border-bottom: 1px solid #e5e5e5; align-items: center; }
.hn-author { font-weight: 600; color: #1a1a1a; }
.hn-updated { color: #c0392b; }
.hn-article-fig { margin-bottom: 24px; }
.hn-article-fig img { width: 100%; }
.hn-article-fig figcaption { font-family: system-ui, sans-serif; font-size: 12px; color: #666; margin-top: 6px; }
.hn-article-body { font-size: 16px; line-height: 1.75; }
.hn-article-body p { margin-bottom: 20px; }
.hn-article-lead { font-weight: 600; font-size: 17px; }
.hn-article-tags { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 24px; padding-top: 16px; border-top: 1px solid #e5e5e5; }
.hn-tag { background: #e5e5e5; padding: 4px 10px; font-family: system-ui, sans-serif; font-size: 12px; border-radius: 2px; }
.hn-related { margin-top: 40px; padding-top: 24px; border-top: 2px solid #c0392b; }
.hn-related-title { font-family: 'Playfair Display', Georgia, serif; font-size: 22px; margin-bottom: 20px; }

/* Static */
.hn-static-page { max-width: 720px; }
.hn-static-body h2 { font-family: 'Playfair Display', Georgia, serif; font-size: 22px; margin: 28px 0 12px; }
.hn-static-body p { margin-bottom: 16px; line-height: 1.7; }

/* Staff */
.hn-staff-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; margin-top: 24px; }
@media (max-width: 700px) { .hn-staff-grid { grid-template-columns: repeat(2, 1fr); } }
.hn-staff-card { background: #fff; border: 1px solid #e5e5e5; padding: 20px; }
.hn-staff-name { font-family: 'Playfair Display', Georgia, serif; font-size: 18px; font-weight: 700; margin-bottom: 4px; }
.hn-staff-title { font-size: 14px; font-style: italic; color: #666; margin-bottom: 4px; }
.hn-staff-beat { font-size: 13px; color: #c0392b; font-family: system-ui, sans-serif; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; margin-bottom: 8px; }
.hn-staff-email { font-family: system-ui, sans-serif; font-size: 13px; color: #c0392b; }

/* Not found */
.hn-not-found { text-align: center; padding: 60px 24px; }
.hn-not-found button { margin-top: 16px; background: none; border: 2px solid #c0392b; color: #c0392b; padding: 10px 20px; cursor: pointer; font-size: 14px; }

/* Footer */
.hn-footer { background: #1a1a1a; color: #aaa; margin-top: 48px; }
.hn-footer-inner { max-width: 1100px; margin: 0 auto; padding: 24px; display: flex; justify-content: space-between; flex-wrap: wrap; gap: 8px; font-family: system-ui, sans-serif; font-size: 13px; }
.hn-footer-links a { color: #aaa; cursor: pointer; }
.hn-footer-links a:hover { color: #fff; }
</style>
